### ISSUE TITLE
Fix and reenable ComplexConditions test

### ISSUE THREAD

**Issue by mrvoorhe** [mono/linker#1000]
The ComplexConditions conditions test was ignored with https://github.com/mono/linker/pull/990.  When the test is ran on windows PeVerify catches invalid IL.

There is a bug in the linker that needs to be fixed so that this test can be reenabled.

To reproduce you need to use monolinker.sln on Windows.  illink.sln does not make use of PeVerify during tests and it seems that pedump is not flagging the invalid IL on non-windows platforms.

**Comment by marek-safar** [comment]
This is the same issue as #975 cause by additional nops
