### ISSUE TITLE
Publish ILLink reference assemblies to NuGet feed

### ISSUE THREAD

**Issue by vitek-karas** [mono/linker#1023]
Investigate the best way to publish the reference assemblies from https://github.com/mono/linker/pull/1014 to a NuGet feed.

Investigate which feed to use.

Implement it and validate the experience of consuming this from a sample custom step project.

@sbomer

**Comment by vitek-karas** [comment]
@marek-safar Do we need the feed to be DARC enabled? That is will the Xamarin SDKs want to auto-update the ref assemblies through DARC or do they want to snap to manually selected version instead?

**Comment by marek-safar** [comment]
DARC is not needed at the moment but the correct versioning of the nuget package will be required for easy check for any API mismatch

**Comment by sbomer** [comment]
Do we want the ref package to be usable by third parties? The way it's set up now is as a shipping package, so Arcade will automatically publish it to the right public feed. From what I can gather, that currently should be `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json`, from https://github.com/dotnet/arcade/blob/master/eng/common/templates/post-build/post-build.yml#L205. However I am noticing that our official build has some issues with the ref assembly that I need to investigate. Once that's fixed, I expect packages will show up here in addition to the dotnet-core feed (which Arcade seems to still publish to, I believe for legacy reasons).

We are also using Arcade to version assemblies and packages. `VersionPrefix` (https://github.com/mono/linker/blob/master/eng/Versions.props#L4) and `PreReleaseVersionLabel` define the assembly/package versions. It's up to us to increment the major/minor/patch numbers as we make changes.
- For ILLink.Tasks, we are using `AutoGenerateAssemblyVersion` as recommended for tools packages, which will cause the assembly to have patch/revision numbers derived from the `OfficialBuildId` (which includes a date and revision). The package will simply have version Major.Minor.Patch, either with or without a suffix depending on whether it's a release official build. Official daily builds have a suffix including `PreReleaseVersionLabel` and a date/revision-based number.
- For the ref assembly package (`illink`), the assembly version will be exactly `VersionPrefix`, and the package version will be the same as above.

I'm not sure whether Arcade will automatically set `DotNetFinalVersionKind` when time comes to make an official release. I think at most we would need to set that property to true in a release branch.

**Comment by marek-safar** [comment]
Having the nuget available on Arcade only is enough for net5. The version prefix needs to be fixed to be something like `5.0.0-preview.1`.

**Comment by sbomer** [comment]
It has been published to `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json`.

**Comment by marek-safar** [comment]
@sbomer the package is up now but it's missing `Mono.Cecil` dependency. I think this should be implicit dependency specified in .nuspec.

**Comment by marek-safar** [comment]
Another question, should we rename the nuget to be just ILLink or ILLinker?

**Comment by sbomer** [comment]
Make sure you are using 'illink', not 'ILLink.Tasks'. The nuspec looks ok to me:
```xml
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>illink</id>
    <version>5.0.0-preview.3.20177.4</version>
    <authors>Microsoft</authors>
    <owners>Microsoft</owners>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <license type="expression">MIT</license>
    <licenseUrl>https://licenses.nuget.org/MIT</licenseUrl>
    <icon>Icon.png</icon>
    <projectUrl>https://github.com/mono/linker</projectUrl>
    <description>IL Linker</description>
    <copyright>© Microsoft Corporation. All rights reserved.</copyright>
    <serviceable>true</serviceable>
    <repository type="git" url="https://github.com/mono/linker" commit="0bf5f0fefceff04470bd3d6919504d39af82a21f" />
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Mono.Cecil" version="0.11.2" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```
And I can reference cecil from a sample project after adding 'illink'.
Yes, we might want to pick a better name. Maybe something like 'Microsoft.NET.ILLink'?

**Comment by vitek-karas** [comment]
@sbomer Is this solved? If so, please close the issue.

**Comment by marek-safar** [comment]
I think it's worth landing the package rename to `Microsoft.NET.ILLink`
