### ISSUE TITLE
[feature/dataflow] Add validation that dataflow annotations match for virtuals

### ISSUE THREAD

**Issue by MichalStrehovsky** [mono/linker#1028]
Need to make sure that e.g. if an interface method has an annotated parameter, all the implementations have a matching annotation. And vice versa.

https://github.com/mono/linker/pull/1024#discussion_r398618497

**Comment by marek-safar** [comment]
I guess this applies to implicit interface implementations only

**Comment by MichalStrehovsky** [comment]
It doesn't matter whether it's explicit or implicit. If this is restricted to implicit only, we wouldn't warn for `A`, but the problem is the same (at the callsite, we don't know we need to preserve the default ctor of X/Y, but the implementation assumes that it was kept (and the CreateInstance is safe).

```csharp
interface IFoo
{
    void A(Type t);
    void B(Type t);
}

class Foo : IFoo
{
    void IFoo.A([DynamicallyAccessed(Constructors)]Type t) => Activator.CreateInstance(t);
    public void B([DynamicallyAccessed(Constructors)]Type t) => Activator.CreateInstance(t);

    static void Main()
    {
        IFoo p = new Foo();
        p.A(typeof(X));
        p.B(typeof(Y));
    }
}
```

**Comment by marek-safar** [comment]
I thought you were describing case like

```c#
interface IFoo
{
    void A([DynamicallyAccessed(Constructors)]Type t);
}
```

Do we have any data which shows this can be actually implemented for at least some real-world cases (putting generics problem aside) ?

**Comment by MichalStrehovsky** [comment]
If the interface is annotated but the implementation isn't, this is less of a problem - it's only weakening the annotation (we ensured linker keeps more stuff than the particular implementation needs - there still might be a different implementation that needs what the interface demands).

This is needed to achieve correctness so I didn't look whether there is real world code using the pattern - if we don't fix this, we could see linker breaking an app without generating a warning about it.

**Comment by marek-safar** [comment]
> if we don't fix this, we could see linker breaking an app without generating a warning about it.

Agree but that essentially means if someone adds DynamicallyAccessed to one of the interface implementations every interface usage has to be annotated as well (kind of scary to think about it for stuff like IEnumerable)

**Comment by vitek-karas** [comment]
Implemented in https://github.com/mono/linker/pull/1315.
