### ISSUE TITLE
Expression.Call/Field/Property pattern match does not work on members from derived classes

### ISSUE THREAD

**Issue by vitek-karas** [mono/linker#1042]
The semantics of `Expression.Call(Type, string, Type [])` is to look for all static public/non-public methods on the specified type and all its base types. Internally it uses `BindingFlags.FlattenHierarchy` to achieve this: https://github.com/dotnet/runtime/blob/d3366b86bc2a1415ae1998334f6a5241b14f0c4f/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/MethodCallExpression.cs#L1172-L1173

The pattern matching in the linker does not look for methods on base types though, so it will not work in all cases.

Example:
```C#
class ABase {
    public static void OnBase() {}
}

class ADerived : ABase {
}

Expression.Call(typeof(ADerived), "OnBase", Type.EmptyTypes);
```

In this case linker will not mark `ABase.OnBase` as reachable and possibly remove it (and it will issue a "warning").

Same problem applies to `Expression.Field(Expression, Type, string)` and `Expression.Property(Expression, Type, string)`.

**Comment by vitek-karas** [comment]
Simple tests for these cases were added in #1043 - but currently they expect the "wrong" behavior.

**Comment by MichalStrehovsky** [comment]
Heh, I made the mistake of looking at Vitek's change in the Runtime repo now and noticed Expressions also use `BindingFlags.IgnoreCase`. We should actually also do case insensitive comparisons with whatever rules reflection implements for this (IIRC reflection does the opposite of how IgnoreCase comparisons are done in .NET - the opposite normalization tends to be observable for the greek sigma character).

I'm really wondering whether we should just mark these as linker unfriendly and ask people to use the overloads that take a PropertyInfo (my assumption is that people would use a more sane binding flag when they get the PropertyInfo manually).

I expect we might see bugs around this for VB programmers - they tend to not care about casing much.

**Comment by vitek-karas** [comment]
Filed https://github.com/mono/linker/issues/1070 to track the case insensitive matching.

**Comment by tlakollo** [comment]
I think this one can already be closed
