### ISSUE TITLE
Linking out of debugging support for .NET5

### ISSUE THREAD

**Issue by marek-safar** [mono/linker#1093]
For .NET5 it would be better to have MSBuild property which controls the debugging support as a complete feature. This would cover the following behavior inside linker.

* [ ] Debug symbols stripping (including embedded PDBs)
* [ ] No special marking of members and types used by the debugger
* [ ] Hook up of hidden features in libraries which keep additional types for debugging

This property could be set automatically when `'$(DebugType)'=='none'`.

**Comment by marek-safar** [comment]
StackFrame tracking at https://github.com/dotnet/runtime/issues/34910

**Comment by eerhardt** [comment]
> Hook up of hidden features in libraries which keep additional types for debugging

There is a similar story with types that are only necessary for COM. See https://github.com/dotnet/runtime/issues/36659. For both COM and debugging, we are "rooting" specific types in the libraries.

For debugging we have:

* https://github.com/dotnet/runtime/blob/b9275463428b6eebb16531aa20e36cfd9d20797f/src/libraries/System.Linq/src/ILLinkTrim.xml#L3-L6
* A bunch in https://github.com/dotnet/runtime/blob/master/src/coreclr/src/System.Private.CoreLib/ILLinkTrim.xml

We could use the same mechanism to preserve and trim these types based on a "feature switch" that is respected in the descriptor XML files.

**Comment by marek-safar** [comment]
@eerhardt could you please look into annotating the debugger dependencies in libraries with correct feature tag. I also think as part of this job we need to figure out how to move SPC XML descriptor to src/libraries

**Comment by eerhardt** [comment]
I believe this issue was addressed for .NET 5. Can it be closed? (I don't have permission to close it)

**Comment by marek-safar** [comment]
There is still unconditional code in libraries for debugger support but I agree it can be closed for linker

**Comment by eerhardt** [comment]
> There is still unconditional code in libraries for debugger support

Do you happen to have an example? I was under the assumption we got all of them.

**Comment by marek-safar** [comment]
Nothing major, mostly stuff like stubbing out the whole System.Diagnostics.Debugger type or conditions like https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskFactory.cs#L1591
