### ISSUE TITLE
Linker should remove the assembly's "linker" resource .xml file

### ISSUE THREAD

**Issue by eerhardt** [mono/linker#1115]
Once we've linked an assembly, it doesn't pay to keep the assemblyName.xml file in its resources.

![image](https://user-images.githubusercontent.com/8291187/79516922-65912880-8012-11ea-8004-8cb35d5128a0.png)

We should remove this .xml file to reduce the size of the assembly.

**Comment by marek-safar** [comment]
ILLinker does that unless you specify `--strip-resources false`. Please fix your build configuration if you need different behaviour.

If you are looking into runtime build output then this is intentional as you see at https://github.com/dotnet/runtime/blob/master/eng/illink.targets#L89

**Comment by eerhardt** [comment]
I figured out why the xml file was still left for my application, it is because I was passing `--ignore-descriptors true`. Should we still be leaving the linker resource .xml file in this case? It feels like it should be removed, even if I told the linker to ignore it.

**Comment by marek-safar** [comment]
I don't think `--strip-resources false` should be overwritten by `--ignore-descriptors true` (the names are not great but you have the flexibility to achieve all combination without any magic). What should work in your case is another custom `--strip-resources true` on the command line

**Comment by eerhardt** [comment]
> What should work in your case is another custom --strip-resources true on the command line

Unfortunately, it doesn't because of this code:

https://github.com/mono/linker/blob/93663d3c03256def21703e3b368557852d891934/src/linker/Linker/Driver.cs#L533-L534

`BlacklistStep` is necessary in order to strip the resources, as far as I can tell, here:

https://github.com/mono/linker/blob/69f31a90085e33dcde1b1ad900ed0c909bac578b/src/linker/Linker.Steps/BlacklistStep.cs#L58-L67

However, `BlacklistStep` never gets executed because `--ignore-descriptors true` is removing it.
If `GetExternalResolveStep (rsc, asm))` is never executed, then nothing is looking at the `.xml` resource, and so nothing is removing it.
