### ISSUE TITLE
Linker is keeping the assembly's "linker" resource .xml with --strip-resources and --ignore-descriptors

### ISSUE THREAD

**Issue by eerhardt** [mono/linker#1125]
I linked my application with options `--strip-resources true` and `--ignore-descriptors true`. When doing this, the linker resource .xml file is still left in System.Private.CoreLib.dll.

I believe this is happening because of this code:

https://github.com/mono/linker/blob/93663d3c03256def21703e3b368557852d891934/src/linker/Linker/Driver.cs#L533-L534

`BlacklistStep` is necessary in order to strip the resources, as far as I can tell, here:

https://github.com/mono/linker/blob/69f31a90085e33dcde1b1ad900ed0c909bac578b/src/linker/Linker.Steps/BlacklistStep.cs#L58-L67

However, `BlacklistStep` never gets executed because `--ignore-descriptors true` is removing it.
If `GetExternalResolveStep (rsc, asm))` is never executed, then nothing is looking at the `.xml` resource, and so nothing is removing it.

This new bug was spawned from this conversation: https://github.com/mono/linker/issues/1115#issuecomment-615370160

cc @marek-safar @vitek-karas

**Comment by marek-safar** [comment]
@sbomer could you look into this?

/cc @vitek-karas
