### ISSUE TITLE
Avoid dynamically changing the pipeline

### ISSUE THREAD

**Issue by sbomer** [mono/linker#1135]
We currently determine the pipeline steps as follows:
- [Get a hard-coded default pipeline](https://github.com/mono/linker/blob/master/src/linker/Linker/Driver.cs#L993)
- During argument parsing:
  - [on `-x`, prepend a `ResolveFromXmlStep`](https://github.com/mono/linker/blob/master/src/linker/Linker/Driver.cs#L443)
  - [on `-a`, prepend a `ResolveFromAssemblyStep`](https://github.com/mono/linker/blob/master/src/linker/Linker/Driver.cs#L457)
- Right after argument parsing:
  - [add/remove steps based on the parsed arguments](https://github.com/mono/linker/blob/master/src/linker/Linker/Driver.cs#L539)
- in `BlacklistStep` (which itself can be removed by `--ignore-descriptors`)
  - [add `ResolveFromXmlStep`s for embedded xml](https://github.com/mono/linker/blob/master/src/linker/Linker.Steps/BlacklistStep.cs#L105)

The argument parsing behavior means that the `-x` and `-a` steps will be run in reverse compared to their order on the command-line.

https://github.com/mono/linker/pull/1132 is adding support for embedded substitution xml (currently using the same pattern as `ResolveFromXmlStep`). To keep the pipeline easy to reason about for custom step authors, we should try to keep it static as much as possible.

@marek-safar which of these behaviors would you like to see changed? In https://github.com/mono/linker/pull/1132#discussion_r412780160 you mentioned that we should avoid updating it while parsing arguments.

Some ideas:
1. Defer adding the `-x` and `-a/-r` steps until after arguments are parsed, while still using one step per file or assembly
2. Use a single `ResolveFromXmlStep` for all `-x` arguments (and a single `ResolveFromAssemblyStep` for all `-a/-r` arguments), plus a step per embedded xml added in `BlacklistStep`.
3. Use a single step for all `-x` args and embedded xml descriptors, having that step track a list of files and `XPathDocument`s to process. This would require `BlacklistStep` to communicate with the single `ResolveFromXmlStep`

I personally think we should at least do 1., adding them to the pipeline in the same order as the command-line arguments. 2. and 3. seem a little less desirable. 2. requires a step to handle either single or multiple inputs, and 3. requires inter-step communication that we don't usually use (and I don't think putting all of the `XPathDocument`s and filenames as `LinkContext` members feels right).

**Comment by marek-safar** [comment]
> I personally think we should at least do 1., adding them to the pipeline in the same order as the command-line arguments

I agree

**Comment by sbomer** [comment]
Closing this since 1. has been done, and I don't think there's any desire to do more. Feel free to re-open if that's not the case.
