### ISSUE TITLE
Linker doesn't support WinRT

### ISSUE THREAD

**Issue by MichalStrehovsky** [mono/linker#1151]
Trying to scan System.Runtime.WindowsRuntime hits problems because linker doesn't seem to handle the projections well. It's possible we'll need features on the cecil side - see jbevain/cecil#394 that has Unity's WinRT support.

It's possible we can just close this as Won't fix when dotnet/runtime#35318 lands, but I think we should track this here for now (so that there's an issue to refer to).

**Comment by eerhardt** [comment]
Note we also have this in dotnet/runtime today:

https://github.com/dotnet/runtime/blob/19cc81be8e31a0d005d860952cf70f6b4ce2b0ae/eng/illink.targets#L65-L67

```xml
    <PropertyGroup>
      <!-- Currently ILLink cannot handle type projections from Windows.winmd, disable if the project references it -->
      <ILLinkTrimAssembly Condition="'%(ReferencePath.FileName)%(ReferencePath.Extension)' == 'Windows.winmd'">false</ILLinkTrimAssembly>
    </PropertyGroup>
```

If this gets fixed, we should be able to fix that. However, we might also need to worry about COM interfaces at that point. See https://github.com/mono/linker/issues/378 and https://github.com/dotnet/corefx/pull/32491#issuecomment-424885963.

**Comment by mrvoorhe** [comment]
In case it's ever of help, here is the logic we have in our UnityLinker to deal with com https://gist.github.com/mrvoorhe/ee5c2d8506e8f7489e683b0ab299e197

We probably have tests somewhere.  Ping me if someone ever wants them.

**Comment by MichalStrehovsky** [comment]
WinRT support won't be needed because .NET 5 WinRT support is moving out of the runtime to external tools that will run before linker.
