### ISSUE TITLE
Linker work for annotating reflection APIs

### ISSUE THREAD

**Issue by vitek-karas** [mono/linker#1178]
Tracking work item for all the issues which are raised as a result of annotating reflection APIs in corelib: 
https://github.com/dotnet/runtime/issues/36229

**Comment by marek-safar** [comment]
Wouldn't it be better to move this to dotnet/runtime where the work will be done?

**Comment by vitek-karas** [comment]
I see this more as a tracking work item - I agree the actual source changes will be in the runtime repo - but there's probably non-trivial impact on the linker as well (as we try to figure out the hard cases).
I can open a "shadow copy" of this in the runtime repo as well.

**Comment by marek-safar** [comment]
OK, Let's move the text to runtime and create or change this one to be about linker changes only and cross-link them

**Comment by vitek-karas** [comment]
Most of the work in CoreLib has been done. We'll open separate issues if we run into new problems.
