### ISSUE TITLE
Assert in RemoveUnreachableBlocks parsing exception handlers

### ISSUE THREAD

**Issue by vitek-karas** [mono/linker#1183]
Running the linker on linux-x64 framework (all public APIs rooted) asserts in https://github.com/mono/linker/blob/ffec224a2a69f0cde4c43d9c90090dcb294ca6c6/src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs#L807

It fails on `System.Text.Encoding.CodePages.dll` in `System.Text.CodePagesEncodingProvider.GetEncoding(int)`. The IL looks like this (beginning is trimmed):
```IL
		IL_007a: callvirt instance void [netstandard]System.Threading.ReaderWriterLockSlim::EnterWriteLock()
		.try
		{
			IL_007f: ldarg.0
			IL_0080: ldfld class [netstandard]System.Collections.Generic.Dictionary`2<int32, class [netstandard]System.Text.Encoding> System.Text.CodePagesEncodingProvider::_encodings
			IL_0085: ldarg.1
			IL_0086: ldloca.s 4
			IL_0088: callvirt instance bool class [netstandard]System.Collections.Generic.Dictionary`2<int32, class [netstandard]System.Text.Encoding>::TryGetValue(!0, !1&)
			IL_008d: brfalse.s IL_0094

			IL_008f: ldloc.s 4
			IL_0091: stloc.3
			IL_0092: leave.s IL_00bd

			IL_0094: ldarg.0
			IL_0095: ldfld class [netstandard]System.Collections.Generic.Dictionary`2<int32, class [netstandard]System.Text.Encoding> System.Text.CodePagesEncodingProvider::_encodings
			IL_009a: ldarg.1
			IL_009b: ldloc.0
			IL_009c: callvirt instance void class [netstandard]System.Collections.Generic.Dictionary`2<int32, class [netstandard]System.Text.Encoding>::Add(!0, !1)
			IL_00a1: leave.s IL_00bb
		} // end .try
		finally
		{
			IL_00a3: ldarg.0
			IL_00a4: ldfld class [netstandard]System.Threading.ReaderWriterLockSlim System.Text.CodePagesEncodingProvider::_cacheLock
			IL_00a9: callvirt instance void [netstandard]System.Threading.ReaderWriterLockSlim::ExitWriteLock()
			IL_00ae: endfinally
		} // end handler
	} // end .try
	finally
	{
		IL_00af: ldarg.0
		IL_00b0: ldfld class [netstandard]System.Threading.ReaderWriterLockSlim System.Text.CodePagesEncodingProvider::_cacheLock
		IL_00b5: callvirt instance void [netstandard]System.Threading.ReaderWriterLockSlim::ExitUpgradeableReadLock()
		IL_00ba: endfinally
	} // end handler

	IL_00bb: ldloc.0
	IL_00bc: ret

	IL_00bd: ldloc.3
	IL_00be: ret
```

The second "catch" block (which is really a finally block) reports `handler.TryEnv.Previous` as instruction `IL_00ba: endfinally` which is an unexpected opcode at this point (we expect all try block to end with a leave instruction)

I tried to prepare the simpler repro, but can't seem to force the C# compiler to generate IL like this - it always inserts the leave instruction into the outer try block.

**Comment by sbomer** [comment]
I recall seeing this error when the last instruction is a throw as well: https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgIwFgBQyDMABGgQMIEDeOB1RhyALAQLIAUAlBVTd8AE4CenbN24BfAgGMAhsAkALISKUFgc3gHsA7gQB2AU20BRAB4S9AB2Bh1O9gG4uS0Y4LPsooA==

**Comment by mrvoorhe** [comment]
If you can't get the compiler to generate the IL, you could write an IL test.  The test framework has support for them.  Ex: https://github.com/mono/linker/blob/master/test/Mono.Linker.Tests.Cases/TypeForwarding/MissingTargetReference.cs
