### ISSUE TITLE
NullReferenceException in Mono.Linker.Steps.RemoveUnreachableBlocksStep.ConstantExpressionMethodAnalyzer.Analyze()

### ISSUE THREAD

**Issue by daz10000** [mono/linker#1198]
Apologies if this is the wrong place for this but I was troubleshooting a build that was originally having issues with netcore3.1 using the current dotnet5 preview to see if error messages would be more informative.  Unfortunately the build instead causes an exception in the Mono linker.   This project is attempting to publish as a single file in case that's relevant.  Here is the stack trace and if this is of interest, can work to try and get you a repro although it's part of a large closed source project so will need to work to extract it unfortunately.   Please let me know if it is of interest'

```
 Fatal error in IL Linker (TaskId:260)
                     Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object. (TaskId:260)
                        at Mono.Linker.Steps.RemoveUnreachableBlocksStep.ConstantExpressionMethodAnalyzer.Analyze() (TaskId:260)
                        at Mono.Linker.Steps.RemoveUnreachableBlocksStep.FindConstantExpressionsMethods(Collection`1 types) (TaskId:260)
                        at Mono.Linker.Steps.RemoveUnreachableBlocksStep.FindConstantExpressionsMethods(Collection`1 types) (TaskId:260)
                        at Mono.Linker.Steps.RemoveUnreachableBlocksStep.Process() (TaskId:260)
                        at Mono.Linker.Steps.BaseStep.Process(LinkContext context) (TaskId:260)
                        at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step) (TaskId:260)
                        at Mono.Linker.Pipeline.Process(LinkContext context) (TaskId:260)
                        at Mono.Linker.Driver.Run(ILogger customLogger) (TaskId:260)
                        at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger) (TaskId:260)
                        at Mono.Linker.Driver.Main(String[] args) (TaskId:260)
16:59:16.793   1:7>C:\Program Files\dotnet\sdk\5.0.100-preview.3.20216.6\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(83,5): error MSB6006: "dotnet.exe" exited with code -1073741819. [C:\src\gsl_web3\src\Demetrix.CLI\DMXFileLoader\DMXFileLoader.fsproj]
                   Done executing task "ILLink" -- FAILED. (TaskId:260)
```

**Comment by daz10000** [comment]
Turns out to be my lucky day - super simple reproduction.  Try `dotnet new console -lang F#` - i.e. template F# console app.  Then edit the project file to publish to singlefile/ trimmed thus

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```

Then try to `dotnet publish`  and it will reproduce the error. (basically publishing an F# app as a singlefile will fail:)  Have seen some similar issue over in the blazor repo I think in my travels.

[Playground4.zip](https://github.com/mono/linker/files/4639480/Playground4.zip)

**Comment by daz10000** [comment]
I have [submitted this](https://github.com/dotnet/runtime/issues/36778)  to the dotnet/runtime repo as well sinice that's tehcnically what is crashing - apologies if redundant and feel free to close whichever is less helpful .

I also refined the repro slightly - you can just do

```
dotnet new console -lang F#
dotnet publish  -p:PublishTrimmed=true --runtime win-x64
```

in an empty folder in your shell (git for me on windows) and produce it.   Trimming is the key step.  It doesn't happen for a simple singlefile publication.  Have not tried for other archs.

**Comment by charlesroddie** [comment]
@daz10000 the F# code created by `dotnet new` involves some of the most difficult code in the language, invoking `sprintf` which is reflection-reliant.

```fsharp
// Learn more about F# at http://docs.microsoft.com/dotnet/fsharp

open System

// Define a function to construct a message to print
let from whom =
    sprintf "from %s" whom

[<EntryPoint>]
let main argv =
    let message = from "F#" // Call the function
    printfn "Hello world %s" message
    0 // return an integer exit code
```

It is not compatible with UWP/CoreRT and possibly the same issue affects F#.

If you remove `sprintf`, does it work?

```fsharp
open System

let from whom =
    "from " + whom

[<EntryPoint>]
let main argv =
    let message = from "F#"
    Console.WriteLine message
    0
```

**Comment by daz10000** [comment]
Apologies,  I just noticed your reply.   I reran the test with the current dotnet5 rc.1 release and it appears to be all fixed so closing this with appreciation.
