### ISSUE TITLE
"Configure the linker for internationalization" doesn't work with illinker.exe

### ISSUE THREAD

**Issue by eerhardt** [mono/linker#1202]
Commit https://github.com/mono/linker/commit/6e0105e0fc16b959510480298599ca09a5509a21 removed support for `-l all|none|mideast|etc` command line switch when building for `FEATURE_ILLINK`. However, Blazor is using this switch (note Blazor uses the `monolinker.exe` now). 

See 
* https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.1#configure-the-linker-for-internationalization
* https://github.com/dotnet/aspnetcore/blob/337b951c15b93675f851005d6f2c95ec539737fc/src/Components/Blazor/Build/src/targets/Blazor.MonoRuntime.targets#L238

If Blazor needs this functionality, should it be added to `illinker.exe`? Or will Blazor only ever use `monolinker.exe` going forward?

cc @marek-safar @vitek-karas

**Comment by marek-safar** [comment]
Blazor integration is being redone (it switches from Mono BCL to .NET Core too) and this option does not make sense.

**Comment by eerhardt** [comment]
Since it is [publicly documented](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.1#configure-the-linker-for-internationalization), will this need to be logged as a breaking change for Blazor?

**Comment by marek-safar** [comment]
or it'll be just no-op property for net5+

**Comment by marek-safar** [comment]
This is tracked in aspnetcore https://github.com/dotnet/aspnetcore/issues/26176
