### ISSUE TITLE
Investigate impact of covariant return overrides on linker

### ISSUE THREAD

**Issue by vitek-karas** [mono/linker#1209]
Per https://github.com/mono/linker/issues/1208 the linker will have to adapt to support the new language and runtime feature "covariant return overrides" - see that issue for more details.

This work item is to investigate the impact on linker. Which areas of linker need to adapt and a rough estimate of how complex that will be.

**Comment by MichalStrehovsky** [comment]
This only affects places that do virtual resolution, so currently the maps built in `TypeMapStep`.

This probably already works. The linker doesn't check whether MethodImpl's are legit (the signature could be completely different and it would still consider the impl to be a valid override and preserve it if the base is used).

I tried throwing one of the tests in the CoreCLR pull request on linker and it did the right thing.

**Comment by vitek-karas** [comment]
Cool - so we really only need to add tests once it's supported by the runtime/compiler, right?

**Comment by MichalStrehovsky** [comment]
> Cool - so we really only need to add tests once it's supported by the runtime/compiler, right?

Yep, we can probably track that in #1208.
