### ISSUE TITLE
Improve diagnostic output when the linker fails

### ISSUE THREAD

**Issue by rolfbjarne** [mono/linker#1233]
When the linker fails, this is the build output:

```
/usr/local/share/dotnet/sdk/5.0.100-preview.6.20269.4/MSBuild.dll -consoleloggerparameters:Summary -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/usr/local/share/dotnet/sdk/5.0.100-preview.6.20269.4/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/usr/local/share/dotnet/sdk/5.0.100-preview.6.20269.4/dotnet.dll -maxcpucount -restore -verbosity:m /bl:log.binlog MySingleView/MySingleView.csproj
  Determining projects to restore...
  Restored /Users/rolf/work/maccore/squashed-onedotnet/xamarin-macios/tests/dotnet/MySingleView/MySingleView.csproj (in 1.48 sec).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  MySingleView -> /Users/rolf/work/maccore/squashed-onedotnet/xamarin-macios/tests/dotnet/MySingleView/bin/Debug/net5.0/ios-x64/MySingleView.dll
/usr/local/share/dotnet/sdk/5.0.100-preview.6.20269.4/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(83,5): error MSB6006: "dotnet" exited with code 1. [/Users/rolf/work/maccore/squashed-onedotnet/xamarin-macios/tests/dotnet/MySingleView/MySingleView.csproj]
```

Just showing a better description than `"dotnet" exited with code 1` when the linker fails would be a nice improvement. Showing all the linker output as proper MSBuild output would be an even better improvement (this way passing `/v:diag` would make verbose output show up, and it would also show up in binary MSBuild logs).

**Comment by sbomer** [comment]
I believe this is much improved with https://github.com/mono/linker/pull/1320 for cases where the linker crashes. Errors that happen during argument parsing still have this problem (see https://github.com/mono/linker/issues/1354).

**Comment by mateoatr** [comment]
We now print all logged errors/warnings and have a clear message when there's a fatal error stating that something went wrong inside the linker -- can this be closed?
