### ISSUE TITLE
Expose linker arguments in MSBuild

### ISSUE THREAD

**Issue by sbomer** [mono/linker#1239]
Arguments need to be exposed in the task https://github.com/mono/linker/blob/master/src/ILLink.Tasks/LinkTask.cs and in in the SDK: https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets#L83.

I am creating this as a tracking issue for all arguments instead of opening a new one each time we add or change linker arguments. Later we should turn this into documentation.

| Status | Command-line | Task | SDK | Notes |
|-|-|-|-|-|
| [X] | `-a` | `RootAssemblyNames` | `TrimmerRootAssembly` | `_ManagedAssembliesToLink` with `IsTrimmable != true`
| [TODO?] | `-r` | - |
| [X] | `-x` | `RootDescriptorFiles` | `TrimmerRootDescriptor` | not set by default |
| [N/A] | `-d` | - |
| [X] | `-reference` | `AssemblyPaths` | `_ManagedAssembliesToLink` | computed from `ResolvedFileToPublish` |
| [TODO] | `-b` | `LinkSymbols` | `_TrimmerLinkSymbols` | SDK defaults need to be changed |
| [TODO?] | `-v` | - |
| [X] | `-out` | `OutputDirectory` | `IntermediateLinkDir` | `linked` directory in intermediate output path |
| [N/A] | `--about` | - |
| [N/A] | `--verbose` | - |
| [N/A] | `--version` | - |
| [N/A] | `-help` | - |
| [X] | `@FILE` | used internally |
| [X] | `-c` | exposed in combination with `-u` via `DefaultAction` | `_TrimmerDefaultAction` | defaults to `copyused` |
| [X] | `-u` | exposed in combination with `-c` via `DefaultAction` | `_TrimmerDefaultAction` | defaults to `copyused` |
| [TODO ] | `-p` | `AssemblyPaths` `Action` string metadata | `_ManagedAssembliesToLink` metadata | defaults to `copy` when `IsTrimmable != true`. Will probably change with https://github.com/dotnet/sdk/issues/12035. |
| **Advanced** |
| [X] | `--custom-step` | `CustomSteps` | `_TrimmerCustomSteps` |
| [TODO] | `--custom-data` | `CustomData` | - | https://github.com/mono/linker/issues/1134 |
| [REMOVE] | `--custom-data ClearInitLocalsAssemblies` | `ClearInitLocalsAssemblies` | removing in https://github.com/mono/linker/pull/1237. see https://github.com/mono/linker/issues/1129 and https://github.com/mono/linker/issues/1256. |
| [TODO?] | `--ignore-descriptors` | - |
| [TODO?] | `--keep-facades` | - |
| [TODO?] | `--skip-unresolved` | - | | set via `_ExtraTrimmerArgs` |
| [TODO?] | `--output-pinvokes` | not exposed |
| **Linking** |
| [TODO?] | `--deterministic` | -|
| [X] | `--disable-opt/--enable-opt` | boolean for global opt, or per-assembly metadata on `AssemblyPaths` |
| [X] | `beforefieldinit` | `BeforeFieldInit` | `_TrimmerBeforeFieldInit` for global opt | not set by default |
| [X] | `overrideremoval` | `OverrideRemoval` | `_TrimmerOverrideRemoval` for global opt | not set by default |
| [X] | `unreachablebodies` | `UnreachableBodies` | `_TrimmerUnreachableBodies` for global opt | not set by default |
| [X] | `clearinitlocals` | `ClearInitLocals` | `_TrimmerClearInitLocals` for global opt | not set by default |
| [X] | `unusedinterfaces` | `UnusedInterfaces` | `_TrimmerUnusedInterfaces` for global opt | not set by default |
| [X] | `ipconstprop` | `IPConstProp` | `_TrimmerIPConstProp` for global opt | not set by default |
| [X] | `sealer` | `Sealer` | `_TrimmerSealer` for global opt | not set by default |
| [TODO?] | `--explicit-reflection` | - |
| [TODO?] | `--keep-dep-attributes` | - |
| [TODO] | `--feature` | `FeatureSettings` | needs to flow from host config settings: https://github.com/dotnet/sdk/issues/11868 |
| [TODO?] | `--new-mvid` | - |
| [TODO?] | `--strip-descriptors` | - |
| [TODO?] | `--strip-security` | - |
| [TODO?] | `--substitutions` | - |
| [TODO?] | `--ignore-substitutions` | - |
| [TODO?] | `--strip-substitutions` | - |
| [TODO?] | `--used-attrs-only` | - |
| [TODO?] | `--attribute-defs` | - |
| **Analyzer** |
| [TODO?] | `--dependencies-file` | - |
| [X] | `--dump-dependencies` | `DumpDependencies` | `_TrimmerDumpDependencies` | may be changing in https://github.com/mono/linker/pull/1228 |
| [TODO?] | `--reduced-tracing` | - | 
| **Additional task options** |
| [X] | `-reference` with `-p skip` | `ReferenceAssemblyPaths` | `ReferencePath` |
| [TODO] | other args | `ExtraArgs` | `_ExtraTrimmerArgs` | `--skip-unresolved` should move to separate option |

**Comment by sbomer** [comment]
@marek-safar could review the ones with a TODO? and let me know if you think we should expose them on the task? I want to be careful about exposing any unstable ones since removing or changing them would be a breaking change for users of the task. We can make such changes, but should be careful about it.

**Comment by marek-safar** [comment]
Good summary. I think all TODO? could wait for now. The most likely candidates to add right now look like `--attribute-defs` (need to use it internally first) and `--deterministic` (if we cannot make it default)

**Comment by sbomer** [comment]
@pranavkm was asking why the linker isn't deterministic. @marek-safar do you think `--deterministic` is ready to be on by default? (Does it need an opt-out?) /cc @vitek-karas

**Comment by pranavkm** [comment]
If the feature exists, it might be cool to have it honor the `Deterministic` property. I wouldn't necessarily expect it to be on be default, since the compiler isn't deterministic by default either.

**Comment by vitek-karas** [comment]
My understanding is that linker has the feature, but it doesn't work 100% - I can't remember the details though - @marek-safar I think you mentioned that there's work left to make it 100% deterministic.

**Comment by marek-safar** [comment]
Correct, there is a work left on linker side to fix bug where -deterministic produces output which linker cannot read
