### ISSUE TITLE
Non-virtual, instance methods that return a constant expression should be inlined

### ISSUE THREAD

**Issue by eerhardt** [mono/linker#1243]
When trying to enable a feature switch to trim away EventSource, I tried replacing the [`EventSource.IsEnabled()`](https://github.com/dotnet/runtime/blob/9abff6e9fbe64a4bb3f4f42888c01ed041f898fb/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L245-L252) method with just `return false;` using a substitutions.xml file. I was able to rewrite the method as a constant:

```xml
  <assembly fullname="System.Private.CoreLib">
    <type fullname="System.Diagnostics.Tracing.EventSource">
      <method signature="System.Boolean IsEnabled()" body="stub" value="false" />
    </type>
  </assembly>
```

From the linked IL:

![image](https://user-images.githubusercontent.com/8291187/83697647-2bc9b080-a5c5-11ea-9e76-82682c2ae36a.png)

However, all the callers of this method are still compiled in:

![image](https://user-images.githubusercontent.com/8291187/83697674-40a64400-a5c5-11ea-9745-3bfa73141207.png)

It seems like this constant should be able to be propagated to the callers, and the branch removed. But from looking at this code, it doesn't happen because of the check here:

https://github.com/mono/linker/blob/29fea6aa0778e7b4e2af0e276c18f968f407a050/src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs#L175-L176

Should non-virtual, instance methods that return a constant expression allow for branch trimming like it does for static methods?

cc @marek-safar @sbomer @vitek-karas @MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
Linker would need to be able to prove the instance is not null.

```csharp
EventLog log = null;
if (log.IsEnabled)
{
    Blah();
}
```

Linker cannot do an optimization that will "fix" this.

**Comment by MichalStrehovsky** [comment]
(C# compiler always emits `callvirt` for instance method calls, even if they're non-virtual, instead of `call` for this specific purpose - the only difference between `callvirt` and `call` for non virtual methods is in the null check.)

**Comment by marek-safar** [comment]
Linked does not do any inlining. In this specific case, it'd need to prove that the constant propagation is side-effect free which is very hard. You'll need to fix this differently.

**Comment by MichalStrehovsky** [comment]
> Linked does not do any inlining

Oh - since this is not an actual inlining, just inlining of the return value - would this actually be possible to do safely?

* If the instance is null, this will throw and we either land in one of the exception handlers (that linker doesn't touch anyway), or we unwind out of the method.
* If the instance is not null, the method is called (and we know what method will get called, because this is a callvirt to a non-virtual method), we know that the return value can't possibly be true. We should be able to eliminate the basic block that handles true.

**Comment by vitek-karas** [comment]
Linker will try to propagate this behavior upstream. So for example if the result of the removal of "true" branch is that the calling method has a simple body with a constant return value, linker will try to repeat that operation on the upstream caller again. Given the null handling I guess we need to make sure that linker will not do that if the method body has any try/catch blocks, as we would be effectively removing those. (It's possible we already handle this correctly).

**Comment by marek-safar** [comment]
I'm worried about all the corner cases, like calling instance method on structs, virtual lookup changes due to some metadata etc. The workaround in code is quite simple so I'm not sure this is worth adding.

**Comment by MichalStrehovsky** [comment]
> Given the null handling I guess we need to make sure that linker will not do that if the method body has any try/catch blocks, as we would be effectively removing those. (It's possible we already handle this correctly).

The key thing is that linker doesn't actually inline - the call is still present. So if the call should throw NullRef, it will throw the NullRef - linker only eliminates the conditional basic block that follows the call.

Nonvirtual method shouldn't be subject to metadata munging (it is an error for the MethodImpl table to refer to a nonvirtual method as either the decl or impl).

**Comment by eerhardt** [comment]
> The workaround in code is quite simple so I'm not sure this is worth adding.

The issue is the shear number of calls to EventSource makes the workaround infeasible.

On [source.dot.net there are 458 references to `EventSource.IsEnabled()`](https://source.dot.net/#System.Private.CoreLib/EventSource.cs,69fcbb5c318fe603,references), and that doesn't include cases where specific EventSource derivatives have wrapper properties around IsEnabled like the [following](https://source.dot.net/#System.Net.Primitives/NetEventSource.Common.cs,2689649fe813490c,references), (which has 40 call sites alone):

```C#
        public static new bool IsEnabled =>
            Log.IsEnabled();
```

Not to mention any usages of EventSource in external libraries. So there are probably thousands of places in the world that would need to change in order to make the calls to EventSource trimmable.

**Comment by marek-safar** [comment]
> The issue is the shear number of calls to EventSource makes the workaround infeasible.

I quickly looked at the libraries code and it's clear we'll have to review every call site anyway because there is some "creativity". On top of that IsEnabled method has multiple overloads and dealing with arguments makes this even more complex.

The `public static new bool IsEnabled =>` code is a good example why I'm reluctant for linker to start verifying the instance call constant propagation is safe.

>Not to mention any usages of EventSource in external libraries

We have no control over that and unless all code is guarded with simple calls IsEnabled it won't trim EvenSource. This is out of scope for .net 5 and we'll probably need different approach (e.g. analyzers) to make any .NET library fully illinker compliant.

**Comment by vitek-karas** [comment]
Discussed offline with @marek-safar , plan is to enable this in a very limited way:
Only perform the constant return value propagation on instance non-virtual methods which are explicitly mentioned in the substitution.xml. Linker will NOT propagate constant values across any random instance non-virtual method. Arguments for this are:
* If fully enabled this could have rather large negative impact on linker performance (basically any property getter would fit the bill) with very questionable gains (in itself it would probably not visibly improve size)
* Still some "fear" of possible issues in corner cases
* We don't have a scenario where we need this to be fully functional everywhere

Once we have that, try it out on the EventSource and see how much it helps and what is left. From that point start a new discussion on how to move forward.

**Comment by vitek-karas** [comment]
Implemented in https://github.com/mono/linker/pull/1274.
