### ISSUE TITLE
Run All Tests not working in VS

### ISSUE THREAD

**Issue by mateoatr** [mono/linker#1259]
Running all tests from Visual Studio isn't working. NUnit stops with the following message:
`An exception occurred while invoking executor 'executor://nunit3testexecutor/': Incorrect format for TestCaseFilter Error: Missing '('. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.` It seems that this is an issue within the communication between NUnit and VS (see https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue691/Issue691). Started failing after https://github.com/mono/linker/commit/0e38c6104af5f27e63e103d2c9930c63e57f0538.

**Comment by marek-safar** [comment]
@sbomer thoughts on this?

**Comment by sbomer** [comment]
I don't think we can do much here other than work around it, either by using `dotnet test` or by disabling the problematic tests. I can look into which ones would need to be disabled.

**Comment by sbomer** [comment]
It seems like most of the signatures (any that include '(' or '#' for example) trigger the bug, so I don't think we want to work around it by disabling tests. For now I suggest using `dotnet test` to run all. It looks like test groups under a project (or individual tests) can still be run from VS.

If https://github.com/nunit/nunit3-vs-adapter/issues/691 isn't fixed soon, I can spend some more time looking for other workarounds, but it would take some understanding of how nunit communicates with VS. It's possible that the testcase data is being filtered using its `ToString()`, in which case there might be a workaround like defining a different `ToString` on the test data types.

**Comment by marek-safar** [comment]
Can this be closed?

**Comment by sbomer** [comment]
It might be worth trying the workaround suggested in https://github.com/nunit/nunit3-vs-adapter/issues/691#issuecomment-646254188. I'll look into it.
