### ISSUE TITLE
Removing unused branches corrupts local scopes in the debugger information

### ISSUE THREAD

**Issue by vitek-karas** [mono/linker#1267]
Repro:
Unzip [PreTrim.zip](https://github.com/mono/linker/files/4765686/PreTrim.zip) which contains the pre-trim S.P.CoreLib.
Run linker with this command line [linker.rsp.txt](https://github.com/mono/linker/files/4765691/linker.rsp.txt) (adapt the paths to local ones).

The problem is in method `System.Globalization.CharUnicodeInfo.GetNumericValueNoBoundsCheck`. The method has two scopes the scope for the entire method and then a nested scope for the last branch (everything after the if).

With the embedded substitutions in the repro dll the last branch is going to be removed (as `IsLittleEndian` is set to `true` always). The `RemoveUnreachableBlocksStep` will remove the instructions at the end of the body, but it will not remove the associated nested scope. This causes problems with the PDB because it now contains scope which is outside of the method body (the scope starts at index 41, but the method body length is 40).

In the end Cecil will write the scope into the PDB with start offset 41 and length -1 -> the -1 is very problematic and will cause "crashes" in subsequent tools.

**Comment by vitek-karas** [comment]
Cleaner way to fix this would be in Cecil itself. [`InstructionCollection.OnRemove`](https://github.com/jbevain/cecil/blob/c1a3c199c31b76e3064316a5f24e176ca780b0af/Mono.Cecil.Cil/MethodBody.cs#L232) already implements cleanup for sequence points, it should also implement cleanup/fixups for local scopes.

Somewhat more interesting question is what should happen in `InstructionCollection.OnAdd` if the insertion is on a local scope boundary. This is not needed for linker (yet?), but if the fix is done in Cecil should probably be done as part of the change.

**Comment by marek-safar** [comment]
Fixed in master and 5.0 release
