### ISSUE TITLE
Ensure RequiresUnreferencedCode is consistent across virtual methods

### ISSUE THREAD

**Issue by MichalStrehovsky** [mono/linker#1271]
Similar to #1028. If I have an interface implementation method marked `RequiresUnreferencedCode`, the interface method itself needs to be marked as such too so that I can't get to `RequiresUnreferencedCode`-method through the interface without triggering a warning.

**Comment by vitek-karas** [comment]
Implemented in https://github.com/mono/linker/pull/1315.
