### ISSUE TITLE
Linker breaks custom marshalers

### ISSUE THREAD

**Issue by MichalStrehovsky** [mono/linker#1281]
If a type is used as `MarshalAs.CustomMarshaler`, we need to keep the `GetInstance` method on it because the runtime is going to call it.

I'm going to mark code that relies on this within the class libraries as linker safe because this is a linker bug.

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.icustommarshaler?view=netcore-3.1

**Comment by marek-safar** [comment]
I think this should be fixed at libraries level. We had something similar in Mono as https://github.com/mono/mono/blob/f3fecf91fb46e720bbee0ae8d62bb073a2b1fcb1/mcs/class/corlib/System.Runtime.InteropServices/MarshalAsAttribute.cs#L49

**Comment by MichalStrehovsky** [comment]
MarshalAsAttribute is a pseudocustom attribute (same as e.g. MethodImplAttribute, DllImportAttribute or StructLayoutAttribute). They will never be emitted as an actual custom attribute into the assembly. I don't think annotating the attribute would fix this.

The fix is probably a one line change here:

https://github.com/mono/linker/blob/c75e8813cc91412cd9033a4bd21f90fd859528cc/src/linker/Linker.Steps/MarkStep.cs#L521-L522

Someone already thought about this, but they wrote code that only takes us half way there.

**Comment by marek-safar** [comment]
Yeah, that sounds indeed much easier
