### ISSUE TITLE
Shortened URL pointing to ILLink helper doesn't go to correct destination

### ISSUE THREAD

**Issue by willdean** [mono/linker#1283]
The URL `https://aka.ms/dotnet-illink` is suggested by `dotnet publish` as giving advice about how to control ILLink/trimming behaviour.

However, at the time of writing, this link resolves to: 
```
https://github.com/mono/linker/blob/master/src/ILLink.Tasks/README.md
```
which isn't useful at all, at least as far as how to control trimmed publishing behaviour.

Could the link-shortener be updated, please?

**Comment by marek-safar** [comment]
The link was updated to point to https://docs.microsoft.com/en-us/dotnet/core/deploying/trim-self-contained
