### ISSUE TITLE
Putting a file extension in an XML descriptor assembly name causes the descriptor elements to be skipped

### ISSUE THREAD

**Issue by eerhardt** [mono/linker#1294]
Create a descriptors xml file like the following:

```xml
<linker>
  <assembly fullname="Microsoft.AspNetCore.Authorization.dll">
    <type fullname="*" required="false" preserve="all" />
  </assembly>
</linker>
```

Note that the assembly fullname has the file extension `.dll` at the end.

When you pass this file into the linker with `-x`, the linker isn't able to resolve the assembly (because it has a `.dll` suffix on it), and the linker will ignore the descriptors in that assembly.

This is how Blazor was generating their descriptor files, and it wasn't working. See https://github.com/dotnet/aspnetcore/blob/cd9da1c3503d89e7f42b7ee780416eb1d4036b84/src/Razor/Microsoft.NET.Sdk.Razor/src/CreateBlazorTrimmerRootDescriptorFile.cs#L35.

We should consider either making this an error/warning, or supporting assembly names with the file extension.

cc @vitek-karas @marek-safar

**Comment by marek-safar** [comment]
I consider this to be a bug on Blazor side. Discussed with @vitek-karas issuing warning in such case.

**Comment by eerhardt** [comment]
> I consider this to be a bug on Blazor side

Agreed. I have https://github.com/dotnet/aspnetcore/pull/23330 to fix it in Blazor. Getting a warning to help diagnose such problems in the future could help save someone's time in the future.

**Comment by vitek-karas** [comment]
#1299 now makes the linker issue a warning in this case.
