### ISSUE TITLE
When linker removes all references to an assembly the assembly ref is not removed 

### ISSUE THREAD

**Issue by ericstj** [mono/linker#1296]
I noticed this when looking at the trimmed assemblies in the .NETCore shared framework.

The assembly System.Diagnostics.TraceSource had a reference to System.Diagnostics.Process in one place which was unreachable and trimmed by the linker, however the assembly ref to System.Diagnostics.Process remains.

Some tools will see this and still try to load Process, the linker should remove this if possible.

**Comment by marek-safar** [comment]
Could you attach the assembly? The illinker removes assembly references in such cases automatically so it's likely there is still some reference to System.Diagnostics.Process somewhere (e.g. in attribute)

**Comment by ericstj** [comment]
Here you go
[System.Diagnostics.TraceSource.zip](https://github.com/mono/linker/files/4833094/System.Diagnostics.TraceSource.zip)

This came from the 5.0.0-preview.6.20305.6 win-x64 shared framework.

Here's the disassembly that shows no references to S.D.Process: https://gist.github.com/ericstj/a73b7511a968d5adb45186e93ef5a166

I can also reproduce by building the System.Diagnostics.TraceSource library in dotnet/runtime, which runs the linker as a post-build step.

**Comment by ericstj** [comment]
@marek-safar did you get a chance to look at this?
