### ISSUE TITLE
iOS: AssemblyDefinition.MainModule.FileName is not set

### ISSUE THREAD

**Issue by rolfbjarne** [mono/linker#1313]
For xamarin-macios, we need the original filename used to load an assembly (because we need to look for specific resources next to that assembly).

However, the AssemblyDefinitions that we get in our custom steps don't have AssemblyDefinition.MainModule.FileName set, which complicates things. It seems like a result of this change: https://github.com/mono/linker/commit/f5a987566eef13ea8f06e1fcfd3680ce307ae51f

A possible solution could be to make https://github.com/mono/linker/blob/da2cc0fcd6c3a8e8e5d1b5d4a655f3653baa8980/src/linker/Linker/AssemblyResolver.cs#L88 accessible from custom steps.

**Comment by MichalStrehovsky** [comment]
We should make `GetAssemblyFileName` a public API.

`ModuleDefinition.FileName` is a useless API because Cecil doesn't provide means to make it work with any other backing streams than a `FileStream` and `FileStream` is a bad choice perf-wise.
