### ISSUE TITLE
Change deterministic output  to be the default linker mode

### ISSUE THREAD

**Issue by marek-safar** [mono/linker#1342]
We have already `--deterministic` option but it's not enabled by default. This is not desirable as the expectation of most developers is to produce reproducible build by default.

The logic behind the option needs to be changed to be enabled by default.

**Comment by vitek-karas** [comment]
Currently this is blocked by https://github.com/jbevain/cecil/issues/680.

**Comment by marek-safar** [comment]
@ViktorHofer this is now implemented
