### ISSUE TITLE
IsTypeInterestingForDataflow logic is not sufficient

### ISSUE THREAD

**Issue by MichalStrehovsky** [mono/linker#1365]
```csharp
		static bool IsTypeInterestingForDataflow (TypeReference typeReference)
		{
			// We will accept any System.Type* as interesting to enable testing
			// It's necessary to be able to implement a custom "Type" type in tests to validate
			// the correct propagation of the annotations on "this" parameter. And tests can't really
			// override System.Type - as it creates too many issues.
			// It also covers TypeBuilder and RuntimeType.
			return typeReference.MetadataType == MetadataType.String ||
				(typeReference.Name.Contains ("Type") && typeReference.Namespace.StartsWith ("System"));
		}
```

We will need to extend this to cover "the type derives from System.Type".

I'm hitting a problem that instance methods on EnumBuilder cannot be annotated because linker is telling me the special `this` parameter annotation cannot be used on EnumBuilders' methods, so linker ignores them, but then I get warnings that the EnumBuilder annotations don't match annotations on virtual methods inherited from System.Type.

I'm worried about perf impact of extending this to checking the base type hierarchy. We probably need a cache.

Cc @vitek-karas

**Comment by MichalStrehovsky** [comment]
We also need to add the [`IReflect`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.ireflect?view=netcore-3.1) interface to the list of interesting types. This is some COM thing that also needs to have annotated methods because it's basically reflection and would allow reflection access because System.Type implements it.

**Comment by vitek-karas** [comment]
Per our offline discussion - let's add a cache for this - the perf impact should be very small and we can try to optimize it once we get to actually optimizing the linker as a whole.

We should get this done "soon" as we need to add the annotations into dotnet/runtime for .NET 5 RC.
