### ISSUE TITLE
Trimming implication of IDispatch

### ISSUE THREAD

**Issue by MichalStrehovsky** [mono/linker#1370]
[IDispatch](https://docs.microsoft.com/en-us/windows/win32/api/oaidl/nn-oaidl-idispatch?redirectedfrom=MSDN) COM interface is basically reflection.

We need to investigate what it means for trimming. Does the runtime provide an implementation of this? If so, linker needs to make this 100% work, or surface warnings somehow.

**Comment by jkoritzinsky** [comment]
Yes, the runtime provides an implementation of `IDispatch` and exposes any interfaces marked with `[InterfaceTypeAttribute (ComInterfaceType.InterfaceIsIDispatch)]`. It also exposes the class type if it is marked with `[ClassInterfaceAttribute]`.

The runtime will also generate an `IDispatch` interface for any type which is `[ComVisible(true)]` or that is in an assembly which is `[ComVisible(true)]` and is not marked `[ComVisible(false)]`. Members of base classes of ComVisible types can be exposed via IDispatch as well.

**Comment by MichalStrehovsky** [comment]
Thanks! I ended up having a thread with Aaron on this. We basically decided that we will just try to detect COM and warn on any usage.

#1382 tries to do at least partial detection and issue warnings. There are way too many ways to get to COM in .NET.
