### ISSUE TITLE
IL2020 is used for two different warnings

### ISSUE THREAD

**Issue by mateoatr** [mono/linker#1379]
This warning code is used for two different scenarios; see [here](https://github.com/mono/linker/blob/95c6b7b715b945a78beeedeade8f9908172aaa0b/src/linker/Linker.Steps/LinkAttributesStep.cs#L121) and [here](https://github.com/mono/linker/blob/cbb0afaecaee3abe7bbba536a44f564198b35456/src/linker/Linker.Dataflow/FlowAnnotations.cs#L114).

There are other `DynamicallyAccessedMembersAttribute` related warnings that don't match any of the warnings listed in the docs (e.g., [IL2022](https://github.com/mono/linker/blob/cbb0afaecaee3abe7bbba536a44f564198b35456/src/linker/Linker.Dataflow/FlowAnnotations.cs#L116)). It seems that these warnings were changed/deleted in the docs without changing some of the places where they were used in #1216.

/cc @tlakollo

**Comment by tlakollo** [comment]
Closed via #1385
