### ISSUE TITLE
Implement property for attribute elements

### ISSUE THREAD

**Issue by mateoatr** [mono/linker#1383]
Requiring users to write arguments for their linker embedded attributes in an order dependent way can cause some trouble. Take the following example:

```C#
class FooAttribute : Attribute {
	public FooAttribute()
	{
	}

	public string A { get; set; } = null;
	public string B { get; set; } = null;
}

...

Bar() {
	// Some logic that checks if A is null and then does something.
}
```

Now imagine I want to embed `[Foo(B = "blah")]` somewhere, I'd try this:
```XML
<attribute fullname="MyAssembly.Foo">
	<argument></argument>
	<argument>b</argument>
</attribute>
```

The linker would then add `[Foo("", "blah")]`, which wasn't my intention.

Additionally, I think that having a way to specify the argument being used would help users document their XML files.

**Comment by marek-safar** [comment]
I'm not sure I follow what is the problem. If you'd like to add attribute and set one of its properties only you could use something like

```xml
<attribute fullname="MyAssembly.Foo">
	<property name="B">bvalue</property>
</attribute>
```

**Comment by mateoatr** [comment]
I hadn't seen anything about this `property` tag when I opened the issue, I now see that it's in the [docs](https://github.com/mono/linker/blob/master/docs/data-formats.md#custom-attributes-elements). Although it's not yet implemented.
