### ISSUE TITLE
Linker warnings should be grouped by type/file

### ISSUE THREAD

**Issue by davidfowl** [mono/linker#1404]
When dumping linker warnings it would be ideal to tackle warnings file by file or type by type but the linker seems to dump warnings in the order in which types of visited. This is understandable by not as ordering the errors by type/file.

**Comment by marek-safar** [comment]
linker does not know about source files and the order there were used for compilation in all the time so that's not a viable option.

However, grouping the marking step warnings on assembly level would make sense to me.

**Comment by mateoatr** [comment]
We could improve the warning experience by caching the warning messages so that we can group them and sort them in a predictable way before printing.

**Comment by davidfowl** [comment]
That would be great 😄

**Comment by mateoatr** [comment]
We've added a `MessageContainer` cache that sorts the warnings and prints them just before the `SweepStep`. The ordering of the warnings is done by [comparing their origin](https://github.com/mateoatr/linker/blob/b7cee486dcc61a782034fcfffef895663e7ebb1d/src/linker/Linker/MessageContainer.cs#L173-L182), if none of the warnings being compared has an attached origin then we compare their warning code.
