### ISSUE TITLE
Nowarn should win over warnaserror

### ISSUE THREAD

**Issue by sbomer** [mono/linker#1415]
Warnings that have been silenced with `nowarn` should not be displayed, regardless of the `warnaserror` settings - even if warnaserror comes last. Currently the `warnaserror` setting will always win regardless of order, which means `nowarn` can't be used to silence warnings if the build has `TreatWarningsAsErrors` set globally.

This is the behavior I see from csc:

```csharp
using System;

namespace con
{
    class Program
    {
        static void Main(string[] args)
        {
            throw new Exception();
            Console.WriteLine("Hello World!");
        }
    }
}
```

```sh
#!/usr/bin/env bash

dotnet "/home/sven/bin/sdk/5.0.100-preview.8.20363.2/Roslyn/bincore/csc.dll" \
/reference:/home/sven/bin/packs/Microsoft.NETCore.App.Ref/5.0.0-preview.8.20361.2/ref/net5.0/System.Console.dll \
/reference:/home/sven/bin/packs/Microsoft.NETCore.App.Ref/5.0.0-preview.8.20361.2/ref/net5.0/System.Runtime.dll \
/out:obj/Debug/net5.0/linux-x64/con.dll /target:exe /nologo \
Program.cs "$@"
```
```
~/con$ ./compile.sh
Program.cs(10,13): warning CS0162: Unreachable code detected
~/con$ ./compile.sh /warnaserror
Program.cs(10,13): error CS0162: Unreachable code detected
~/con$ ./compile.sh /nowarn:CS0162 /warnaserror
~/con$
```

@mateoatr

**Comment by XtroTheArctic** [comment]
This still doesn't work using the Directory.Build.props file.

Can anyone give me a workaround solution?

```
<Project>
  <PropertyGroup>
    <NoWarn>CS0162</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
```

**Comment by XtroTheArctic** [comment]
Sorry. In the opposite order, it seems to be working fine.

```
<Project>
  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>CS0162</NoWarn>
  </PropertyGroup>
</Project>
```

**Comment by XtroTheArctic** [comment]
No still not working. It worked for once somehow but after modifying the C# code and recompiled, it fails again :(

**Comment by XtroTheArctic** [comment]
This is messed up. It fails after changing the code and recompiling. Then it works fine after a secondary, redundant recompile... I think this is a bug in the compiler (or linker).

**Comment by sbomer** [comment]
@XtroTheArctic this issue was specifically about the behavior of ILLink which has been fixed (the csc example was just for comparison). For bugs in the compiler warning behavior you should file an issue at https://github.com/dotnet/roslyn.

That said, I wasn't able to observe the behavior you mentioned. On my machine it works exactly as I would expect, using `dotnet build` - the `NoWarn` wins and I never get an error on the first or any subsequent build. If you file a new issue, it would be helpful to include a specific set of repro steps to help us root cause the issue. Thanks!
