### ISSUE TITLE
Linker should warn when `DynamicallyAccessedMembersAttribute` is used on an item which is not type-like

### ISSUE THREAD

**Issue by vitek-karas** [mono/linker#1420]
We already warn about using the attribute on a method directly (as that is meant for special cases when we need to annotate the "this" parameter).

But we don't warn when the attribute is placed on the wrong thing - for example a property of type `System.Object`. In that case linker silently ignores the attribute.

**Comment by vitek-karas** [comment]
@MichalStrehovsky what do you think?
I personally don't see a problem with adding the warning instead of silently ignoring it.

**Comment by MichalStrehovsky** [comment]
Yup, that might be good. I think the only reason why we chose not to do anything about it is perf - so that we don't have to check for the attribute. The perf impact might be just in the noise range though.

**Comment by vitek-karas** [comment]
We already check for the attribute as far as I can tell pretty much everywhere. The `FlowAnnotations.BuildTypeAnnotations` does that. And it has an explicit check if it's on an "interesting type" - currently we just skip the member if it's not interesting - the proposal is to swap the checks - look for attribute first and then do the interesting check - if there's an attribute but it's not interesting - log a warning.

**Comment by MichalStrehovsky** [comment]
Yeah, the "is interesting" check was supposed to be a quick filter, until it turned out to be... not that quick because it has to walk base hierarchy instead of doing a simple name check. It might even be a perf improvement to swap the checks, as most things don't have any attributes.
