### ISSUE TITLE
IL1005: Error processing method 'System.Void LinkerTest.LicenseManager`1/ProductType::.ctor()'

### ISSUE THREAD

**Issue by IrinaPykhova** [mono/linker#1439]
Repro app:
[LinkerTest.zip](https://github.com/mono/linker/files/5096111/LinkerTest.zip)

I'm trying to publish .Net 5 application (use attached sample which shows stripped code reproducing the problem) from VS UI to local folder with these publishing options:

![PublishingOptions](https://user-images.githubusercontent.com/19591075/90630596-c20f8900-e23a-11ea-91b2-0f19dd8dd725.jpg)

It fails every time with the same error, **here is complete error log**:

19.08.2020 16:30:37
System.AggregateException: One or more errors occurred. ---> System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. <---

System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 

**stack trace from VS output:**
2>--skip-unresolved true 
2>
2>Mono.Linker.LinkerFatalErrorException: e:\Projects\LinkerTest\Form1.cs(51,17): error IL1005: LinkerTest.LicenseManager`1/ProductType::ProductType(): Error processing method 'System.Void LinkerTest.LicenseManager`1/ProductType::.ctor()' in assembly 'LinkerTest.dll'
2> ---> System.Exception: Exception of type 'System.Exception' was thrown.
2>   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.WarnAboutInvalidILInMethod(MethodBody method, Int32 ilOffset)
2>   at Mono.Linker.Dataflow.MethodBodyScanner.Scan(MethodBody methodBody)
2>   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.ScanAndProcessReturnValue(MethodBody methodBody)
2>   at Mono.Linker.Steps.MarkStep.MarkReflectionLikeDependencies(MethodBody body, Boolean requiresReflectionMethodBodyScanner)
2>   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
2>   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
2>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
2>   --- End of inner exception stack trace ---
2>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
2>   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
2>   at Mono.Linker.Steps.MarkStep.Process()
2>   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
2>   at Mono.Linker.Pipeline.Process(LinkContext context)
2>   at Mono.Linker.Driver.Run(ILogger customLogger)
2>"dotnet.exe" exited with code 1.

**Comment by marek-safar** [comment]
Please reopen the issue if you are still experiencing it with .NET5 RTM
