### ISSUE TITLE
LinkContext.GetAssemblies should be exposed in the reference assembly

### ISSUE THREAD

**Issue by rolfbjarne** [mono/linker#1455]
Xamarin.iOS needs the list of assemblies that are loaded in the linker, and the lack of LinkContext.GetAssemblies makes this more complicated than it should be (we have a custom step we inject after the LoadReferencesStep that overrides ProcessAssembly and collects the assemblies).

Adding LinkContext.GetAssemblies to the reference linker assembly would make this extra code unnecessary.

This is one place where we're using LinkContext.GetAssemblies now: 

https://github.com/xamarin/xamarin-macios/blob/f613eacd9b80838924571e8e8452596a3fb50e0f/tools/linker/ApplyPreserveAttribute.cs#L32-L39

**Comment by marek-safar** [comment]
Having the custom step is the right approach instead of using GetAssemblies. We could add the API but there is high-risk it will be used wrongly as in your ApplyPreserveAttribute.cs case.
