### ISSUE TITLE
AnnotationStore.AddPreservedMethod (MethodDefinition key, MethodDefinition method) should be in the reference assembly

### ISSUE THREAD

**Issue by rolfbjarne** [mono/linker#1456]
The method AnnotationStore.AddPreservedMethod (MethodDefinition key, MethodDefinition method):

https://github.com/mono/linker/blob/2b04c065c84aa8f30600e3b1989c537fc77de95b/src/linker/Linker/Annotations.cs#L402-L405

is not in the reference assembly (a different overload is there):

https://github.com/mono/linker/blob/763e8acb9a6c1e5e3e391ce9bcd3b71a13356caf/src/linker/ref/Linker/Annotations.cs#L22-L25

Xamarin.iOS uses this method to preserve a method if another method is preserved:

https://github.com/xamarin/xamarin-macios/blob/d5ddc920e760c116e01395bb98dd22f2af81abc4/tools/linker/MonoTouch.Tuner/PreserveSmartEnumConversionsSubStep.cs#L44-L51

**Comment by radekdoulik** [comment]
I would like to use that method in XA custom step as well, to replace code like https://github.com/xamarin/xamarin-android/blob/d471b4a4308310afb8fa3fa1047003a7caedd57f/src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs#L437, where we need to move it outside of MarkStep.
