### ISSUE TITLE
ILLink failed with exit code -532462766. 

### ISSUE THREAD

**Issue by marek-safar** [mono/linker#1457]
---
**Issue moved from dotnet/runtime#41275**
- Please respond to @NakWarsi.

---

_From @NakWarsi on Monday, August 24, 2020 5:27:45 AM_

I am trying to import OPCUA Client library in Client-side Blazor project and I am getting the linking issue,
followings are the compile-time error I am getting,
```
_Severity Code Description Project File Line Suppression State
Error Unhandled exception. Mono.Linker.LoadException: Error while processing references of 'Opc.Ua.Server, Version=1.4.362.0, Culture=neutral, PublicKeyToken=bfa7a73c5cf4b6e8' OpcUa Client C:.....nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.1\targets\Blazor.MonoRuntime.targets 326
Error ILLink failed with exit code -532462766. OpcUa Client C:.....nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.1\targets\Blazor.MonoRuntime.targets 326
```

if I make BlazorWebAssemblyEnableLinking(as following) false, the error goes out but the project doesn't have the reference of the library on the browser so we need it,
true

Help needed,

**Comment by marek-safar** [comment]
---
**Issue moved from dotnet/runtime#41275**
- Please respond to @Dotnet-GitSync-Bot.

---

_From @Dotnet-GitSync-Bot on Monday, August 24, 2020 4:33:00 PM_

I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one [area label](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md).

**Comment by marek-safar** [comment]
---
**Issue moved from dotnet/runtime#41275**
- Please respond to @msftbot[bot].

---

_From @msftbot[bot] on Tuesday, August 25, 2020 3:11:56 PM_

Tagging subscribers to this area: @vitek-karas, @agocke
See info in area-owners.md if you want to be subscribed.

**Comment by marek-safar** [comment]
---
**Issue moved from dotnet/runtime#41275**
- Please respond to @vitek-karas.

---

_From @vitek-karas on Tuesday, August 25, 2020 7:25:38 PM_

Would it be possible to share a repro project? Or at least the NuGet reference you're trying to add which causes problems...

**Comment by marek-safar** [comment]
---
**Issue moved from dotnet/runtime#41275**
- Please respond to @marek-safar.

---

_From @marek-safar on Tuesday, August 25, 2020 9:25:58 PM_

Could you try to upgrade to .NET5 version and report back if the issue still persist?

**Comment by marek-safar** [comment]
---
**Issue moved from dotnet/runtime#41275**
- Please respond to @msftbot[bot].

---

_From @msftbot[bot] on Wednesday, August 26, 2020 8:31:32 PM_

Tagging subscribers to this area: 
See info in area-owners.md if you want to be subscribed.

**Comment by marek-safar** [comment]
---
**Issue moved from dotnet/runtime#41275**
- Please respond to @ericstj.

---

_From @ericstj on Wednesday, August 26, 2020 8:32:21 PM_

@marek-safar not sure where the best place for linker bugs is in dotnet/runtime, but let's keep them out of area-meta as that doesn't get the right eyes on them.

**Comment by amitavraham** [comment]
Getting the same issue 
It happens when I try to publish the app
The app is a blazor wasm application 

    TargetFramework: netstandard2.1
    RazorLangVersion: 3.0

another thing that is seen whenever this issue is manifesting itself is 
unhandled exception. Mono.Linker.MarkException: Error processing method: 'System.String Microsoft.Net.Http.Headers.DateTimeFormatter::ToRfc1123String(System.DateTimeOffset,System.Boolean)' in assembly: 'Microsoft.Net.Http.Headers.dll'	TestApp.Client	C:\Users\User\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.1\targets\Blazor.MonoRuntime.targets	326	

The issue is always link to this code
<BlazorILLink
        ILLinkPath="$(ComponentsWebAssemblyLinkerPath)"
        AssemblyPaths="@(_BlazorAssemblyToLink)"
        RootAssemblyNames="@(_BlazorLinkerRoot)"
        RootDescriptorFiles="@(BlazorLinkerDescriptor)"
        OutputDirectory="$(_BlazorIntermediateLinkerOutputPath)"
        ExtraArgs="$(_BlazorLinkerAdditionalOptions)"
        ToolExe="$(_DotNetHostFileName)"
        ToolPath="$(_DotNetHostDirectory)" />

I hope someone can help

**Comment by marek-safar** [comment]
Could you share a repro we could use to track this down?

**Comment by amitavraham** [comment]
No point in investing time on this issue. I just updated to .net5.0 and issue is gone.

**Comment by marek-safar** [comment]
@amitavraham thanks for letting us know

**Comment by Perun89** [comment]
Bump. And I connot switch to .NET5.0 ATM.
