### ISSUE TITLE
Linker tests should not use %TEMP% as the location for temporary files

### ISSUE THREAD

**Issue by vitek-karas** [mono/linker#1479]
Effects of using %TEMP% which are not desirable:
* Running tests from two clones of the repo at the same time in parallel will not work (the tests will access the exact same path/files)
* In theory the tests should not need to access anything outside of the repo clone
* If the tests fail they may leave "garbage" in "dirty" the machine they're running on
* On Windows AV may affect the tests - I personally disable AV on the repo clone as it doesn't work well with lot of new executables generated all the time (finds false positives and makes thing generally slower). But tests will produce files into %TEMP% which is a location I definitely don't want to disable AV for. I just ran into a case where the tests failed because AV thought that the generate `test.exe` is malicious and deleted it.

**Comment by marek-safar** [comment]
I think it would be better to generate temporary tests files under artifacts/ folder with unique path (to enable parallel runs)

**Comment by ViktorHofer** [comment]
CoreClr is doing the same but I wouldn't recommend to borrow that logic as it could be drastically improved.

**Comment by mateoatr** [comment]
> CoreClr is doing the same but I wouldn't recommend to borrow that logic as it could be drastically improved.

I'm curious how you think we can improve this without following the runtime steps.

**Comment by ViktorHofer** [comment]
So putting the wrappers into the artifacts folder is fine but we should also think about a) restorability and b) extension points. Restorability means, we need to set the intermediate paths correctly so that asset files are chosen correctly for the wrappers. With extension point I mean making sure that SDK defaults like Directory.Build.* imports are set correctly so that it doesn't randomly pick one from the artifacts folder.

**Comment by marek-safar** [comment]
There is no need to pull any msbuild dependencies here. There is already code written to handle the sandboxing fully, we only need to tweak it to do the sandboxing in machine-wide unique location

**Comment by tlakollo** [comment]
Closing since https://github.com/mono/linker/pull/1684 already fix this
