### ISSUE TITLE
Unhandled Exception in IL Linker when trimming vbproj

### ISSUE THREAD

**Issue by fitdev** [mono/linker#1496]
I get IL Linker `System.NullReferenceException` when trimming vbproj with some 3rd party .NetFramework-based assembly references (not sure if this fact is relevant though).

```
 Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Linker.CustomAttributeSource.HasCustomAttributes(ICustomAttributeProvider provider)
     at Mono.Linker.AnnotationStore.HasLinkerAttribute[T](IMemberDefinition member)
     at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider, DependencyInfo& reason, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkProperty(PropertyDefinition prop, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type, Boolean includeBaseTypes, DependencyInfo& reason, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.Initialize()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
```

```
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Publish command used:

```
dotnet publish -r win-x86 --self-contained=true -p:PublishTrimmed=true -p:PublishSingleFile=true "MyProject.vbproj"
```

Relevant project settings:

```xml
  <PropertyGroup>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>copyused</TrimMode>
    <SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
  </PropertyGroup>
```

**Comment by tlakollo** [comment]
I was trying to create some tests that exercise this callstack and could generate a NullReferenceException, but I couldn't find the right combination. Could you share more details on how to reproduce this issue?

**Comment by fitdev** [comment]
What information do you need? I am happy to provide more details, but I don;t know what would be useful. Unfortunately I cannot share assemblies themselves. Could this be related to the fact that some assemblies are real old, like from the .Net Framework 2 and 3.5 timeframe?

**Comment by tlakollo** [comment]
I don't think that would be the case, the code is trying to find custom attributes. I don't see why Custom Attributes would have problems due to .Net Framework. 
In order to investigate more:
-Are you using a xml file with the linker? It would be important to see a snipet of the xml in case you are using the `--link-attributes` option. I didn't saw it in the publish command but need to ask since it would be an important piece of info.
-Could you install the latest sdk from 5.0 RC2 (available at https://github.com/dotnet/installer) and see if the problem presist. This is just to discard that some of the latest changes fixed the issue.
-Can you delete the "/bin" "/obj" folders in the project and run the publish command with "-v:n" and see if there is more information that you consider relevant

If these steps don't help with the debugging we could also discuss on how to setup a private environment where you can upload a crashdump of the failure if that is something you can do.

**Comment by fitdev** [comment]
Thank you for looking into this and for the tips.

No, I am not using any customizations like xml file. At this stage I just wanted to test how it works with the defaults and so far was not able to use trimming feature regardless of the `TrimMode` setting (fails with the same error all the time).

I will let you know of my results with RC2 once it becomes officially available (hopefully soon) (don't want to risk polluting my SDK installs with non-oficially-released SDKs to avoid further issues).

I will run the command with the extra arguments as you suggested and let you know if I see anything of relevance.

**Comment by fitdev** [comment]
Might this issue have something to do with one of the old .Net Framework-based 3rd party libraries referencing `System.Web.UI` types - either attributes in metadata or just types in IL? Would this produce such an error, since `System.Web.UI` is not in .Net Core / .Net 5? If so, it would be nice to have linker simply completely remove those members / types / metadata that reference such non-existing APIs.

**Comment by agocke** [comment]
I suspect it's probably something related to the assembly graph being constructed -- referencing .NET Framework assemblies from .NET Core isn't supported, so it's likely an implicit dependency got dropped somewhere.

**Comment by fitdev** [comment]
Just a suggestion then: considering the project runs just fine, would it then be possible to have an option (or a default behavior) in the linker to basically completely remove / ignore references (in code and metadata) to unresolved types/assemblies?

I think this may be a major issue preventing people from using the linker at all, at least as far as porting legacy .Net Framework -based projects goes. It _is not always possible_ to have a source for an "ancient" library to recompile it for .Net 5+, but it _is often easy_ to avoid using certain parts of it that depend on obsoleted APIs. In other words, one can usually adjust the consumption of an old library in their app by changing a few things, or at most removing a few IL instructions from the library itself; whereas recompiling such a library to be compatible with .Net 5+ might prove impossible. And given that it is possible for an app to run just fine on .Net 5+, it's a pity if the linker technology could not be utilized because of a few _unused_ (at runtime) references in the library to obsoleted types / assemblies.

**Comment by fitdev** [comment]
I managed to recompile all 3rd party libs to target net5, removing all references to the missing types. This solved the issue with the linker and it no longer crashed. So, it is likely that the culprit was missing types that were referenced by 3rd party assemblies. Still, I think you should account for this scenario, as it would be quite common one when porting .Net Framework apps to .Net Core. In my case there were several attributes from System.Web.UI with which some members/types in the 3rd party assemblies were annotated.

**Comment by tlakollo** [comment]
With #1535 now the code will throw an exception on custom attribute unresolved reference if the --ignore-unresolved option was not passed. If --ignore-unresolved flag is set the custom attribute will be skipped (deleted) and the execution will continue.
