### ISSUE TITLE
Runtime error due to inability to load mscorlib in a conservatively trimmed app

### ISSUE THREAD

**Issue by fitdev** [mono/linker#1522]
I am using .Net 5 RC1.
These are my trim settings:

```xml
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <PublishTrimmed>false</PublishTrimmed>
    <TrimMode>copyused</TrimMode>
    <SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
```

And the command line:
```
dotnet publish -c Release -r win-x86 --self-contained=true -p:PublishTrimmed=true -p:PublishSingleFile=false "MyProject.vbproj"
```

The linker does a good job and reduces the app from ~160MB to ~100MB. However when I run the trimmed app I get the following exception:

```
Type = System.IO.FileNotFoundException
Message = Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
TargetSite = InternalLoad
Source = System.Private.CoreLib
StackTrace =    at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark
 stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Runtime.Serialization.Formatters.Binary.Converter..cctor() = 
```

Upon examining the [source](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/Formatters/Binary/Converter.cs) of `System.Runtime.Serialization.Formatters.Binary.Converter` I discovered that it loads from somewhere `mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089` assembly. Apparently trimming messes this up somehow. I tried copying the `mscorlib.dll` from the untrimmed folder to the trimmed folder, but it has no effect - still get the error.

**Comment by agocke** [comment]
`BinaryFormatter` is currently not safe for trimming, but because the type is [obsolete as of .NET 5](https://github.com/GrabYourPitchforks/docs/blob/bf_obsoletion_docs/docs/standard/serialization/resolving-binaryformatter-obsoletion-errors.md) it's unlikely that we'll make any changes to make it trimming safe.

There is ongoing work to make other serializers, like `System.Text.Json` safe for trimming, although there are still known issues that we're working through.

**Comment by fitdev** [comment]
The problem is with old 3rd party libraries (dependencies), of which we have no control (source-code-vise). So this effectively then prevents usage of trimming. The issue however is not with using `BinaryFormatter` (we do not use it in the app directly),  but with the fact that the code for it is in .Net 5 RC1 (albeit being obsoleted, as you said) and the error occurs _during type initialization by the runtime_ when it tries to initialize field:
```cs
        // In .NET Framework the default assembly is mscorlib.dll --> typeof(string).Assembly.
        // In Core type string lives in System.Private.Corelib.dll which doesn't
        // contain all the types which are living in mscorlib in .NET Framework. Therefore we
        // use our mscorlib facade which also contains manual type forwards for deserialization.
        internal static readonly Assembly s_urtAssembly = Assembly.Load("mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
```
So, perhaps you can suggest a workaround for this issue? Why copying the `mscorlib.dll` from the _un_trimmed folder to the trimmed folder does not resolve it: it still says it cannot find the assembly.

**Comment by MichalStrehovsky** [comment]
> Why copying the mscorlib.dll from the _un_trimmed folder to the trimmed folder does not resolve it: it still says it cannot find the assembly.

There's a *.json file listing all assemblies that comprise the app. I haven't tried, but maybe if you add an entry for mscorlib in the json (together with copying the assembly from the untrimmed to the trimmed folder), the runtime will be able to find it.

**Comment by MichalStrehovsky** [comment]
(You'll find the *.json file in the trimmed folder.)

**Comment by fitdev** [comment]
@MichalStrehovsky Thanks so much! It worked perfectly!

**Comment by fitdev** [comment]
Just thought I would mention that strangely enough, when I use a supposedly more aggressive global trimming mode (`link`), the `mscorlib.dll` _was kept_. While when I use more inclusive trimming mode (`copyused`), `mscorlib.dll` _was NOT kept_. This is counterintuitive and altogether strange.
