### ISSUE TITLE
Skip entire assembly

### ISSUE THREAD

**Issue by xcap2000** [mono/linker#155]
Is it possible to skip an entire assembly from the xml descriptor file? If positive how?

**Comment by mrvoorhe** [comment]
See 
https://github.com/mono/linker/blob/master/linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedAssemblyWithNoDefinedPreserveHasAllTypesPreserved.cs
and
https://github.com/mono/linker/blob/master/linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedAssemblyWithNoDefinedPreserveHasAllTypesPreserved.xml
