### ISSUE TITLE
Lazy loading refactoring

### ISSUE THREAD

**Issue by agocke** [mono/linker#1574]
The linker needs to be able to load assemblies that are seen through `DynamicDependencyAttribute` the same as it loads assemblies seen from the start, which includes correctly reading and processing the associated XML files.

Pieces:

- [ ] Lazy type loading

**Comment by agocke** [comment]
@sbomer Creating this as more of an Epic -- feel free to create sub-issues or more checkboxes to detail all of the work.

**Comment by marek-safar** [comment]
We already have a task for this created as #1164

**Comment by agocke** [comment]
Dup of #1164
