### ISSUE TITLE
SRE types not linked out

### ISSUE THREAD

**Issue by vargaz** [mono/linker#1588]
To reproduce:
- Add to HelloWorld.csproj:
```
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>link</TrimMode>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>osx-x64</RuntimeIdentifier>
```
- Run dotnet publish

Actual result: the SRE types like DynamicMethod,FieldBuilder etc. are still present along with their virtual methods despite
having no constructors left and the runtime doesn't construct them either.

**Comment by marek-safar** [comment]
I have a fix for that just need to PR it

**Comment by marek-safar** [comment]
This should be fixed in the latest version. Please let me know if you still see some code (I could use different test)

**Comment by vargaz** [comment]
This still seems to happen with master of dotnet/runtime which contains the linker bump. To reproduce, run ```make``` in ```src/mono/netcore/samples/console``` and check
```bin/Release/publish/managed/System.Private.CoreLib.dll```

**Comment by akoeplinger** [comment]
I also still see them with the wasm console sample.

**Comment by vargaz** [comment]
This seems to be fixed now.
