### ISSUE TITLE
Custom steps can't use error codes outside [1000, 2000]

### ISSUE THREAD

**Issue by rolfbjarne** [mono/linker#1596]
Creating an error message for an error code outside of the range of [1000, 2000] results in:

    Unhandled exception. System.ArgumentException: The provided code '8000' does not fall into the error category, which is in the range of 1000 to 2000 (inclusive). (TaskId:134)
        at Mono.Linker.MessageContainer.CreateErrorMessage(String text, Int32 code, String subcategory, Nullable`1 origin) (TaskId:134)
        at Xamarin.Linker.LinkerConfiguration.Report(IList`1 exceptions) (TaskId:134)

Yet the documentation says to not use that range: "The known codes are in the range 1000 to 6000. Custom steps should avoid using this range not to collide with existing or future error and warning codes." (https://github.com/mono/linker/blob/7e27fb84e68f88d7d9082af16740117ff7985e61/docs/error-codes.md#illink-errors-and-warnings)

**Comment by marek-safar** [comment]
@mateoatr could you look into that?
