### ISSUE TITLE
RequiresUnreferencedCode does not produce warning if the method is not seen in a call instruction

### ISSUE THREAD

**Issue by vitek-karas** [mono/linker#1607]
Linker can mark methods through various means, only one of which is seeing a direct call instruction. Some of other cases:
* Using reflection like `GetMethod` via intrinsic handling
* Through `DynamicallyAccessedMembers` annotation which ends up marking methods sometimes
* Marking of virtual methods on instantiated types
* Marking of interface methods for instantiated types
* several other cases

Currently the linker only recognizes the `RequiresUnreferencedCode` attribute when analyzing method body instructions, then it reports a warning for calls to method with such attribute. If the method with such attribute is marked for any other reason linker will not produce the warning.

But if linker decides to keep the method (that is, the method is marked) and it is also annotated with `RequiresUnreferencedCode` attribute, linker should always report a warning since such method is potentially reachable.

**Comment by MichalStrehovsky** [comment]
This should probably extend to methods that have DynamicallyAccessedMembers annotations - it would fully address the TODO on line 113 in https://github.com/mono/linker/blob/bae5bd8d2ea60ff40713844e8c4c4c928c7c5741/docs/design/reflection-flow.md.

**Comment by vitek-karas** [comment]
Adde a sample test in https://github.com/mono/linker/pull/1608 - it should be enabled along with the fix.

**Comment by vitek-karas** [comment]
Didn't realize that this is going to be a bit tricky:
* If there is a `call` to the method, then we would probably raise the warning twice with a simple solution - not ideal
* If there is a call and there's intrinsic handling of it - we may not want to raise a warning at all (for example `MakeGenericType` is like that)
* `DynamicallyAccessedMembers` is going to be even more tricky - since it pretty much always has intrinsic handling, but if we don't see a call we want to provide some generic warning message (since we can't use the specific ones since we don't know what value is passed to where).
  * Note that this should not react to annotations on return value - since those do not impose new requirements on the "caller" which is the actor in this case
  * Similarly this would apply to `out` parameters, but we probably don't have a good handling of those currently - so it's safer to warn in that case just to be sure.
  * This will probably need special handling of properties - if the property getter or setter is annotated we won't see the access to it via reflection usage typically (since the typical pattern is `GetProperty().SetMethod` ) so we will have to react to this when we mark the property on its own (even if it has annotation only on the setter). Similarly for events if we care about those.
