### ISSUE TITLE
Better handling of a library trimming

### ISSUE THREAD

**Issue by marek-safar** [mono/linker#1610]
ILLinker does not have a good concept of a library trimming. The initial approach was made with `-r assembly` options but it's incomplete.

There is a conceptual problem because options `-a` and -`r` are not exclusive, one can use the same assembly or assemblies with both modes at the same time. We should probably break this expectation and allow only one mode at the same time. This would allow us to set different defaults in library mode which is used mostly for IL trimming only.

The list of settings which would be set differently in this mode (unless set manually)
- --strip-link-attributes false
- --strip-substitutions false
- --strip-descriptors false
- --disable-opt unusedinterfaces
- --disable-opt overrideremoval
- --disable-opt unusedtypechecks

@vitek-karas @sbomer

**Comment by sbomer** [comment]
Probably also:
- --keep-dep-attributes true

Related: https://github.com/mono/linker/issues/1541.
