### ISSUE TITLE
Signing issue in official build

### ISSUE THREAD

**Issue by akoeplinger** [mono/linker#1654]
Looking at https://dev.azure.com/dnceng/internal/_build?definitionId=352&_a=summary it seems it started about a week ago on Nov 20, both on release/5.0 and master but I can't see a commit that would've caused it so probably some infrastructure issue?

/cc @marek-safar @vitek-karas

**Comment by marek-safar** [comment]
I suspect this has something to do with missing arcade update. We had similar problems on PR builds and they were resolved by arcade update.

**Comment by marek-safar** [comment]
It seems to be resolved, closing.
