### ISSUE TITLE
Is there a way to merge the same assembly?

### ISSUE THREAD

**Issue by ivan-prodanov** [mono/linker#1678]
LibA has the following dependency trimmed using the linker (illink):
- LibShared

LibB has the following dependency trimmed (differently than LibA) using the same linker:
- LibShared

Is there a way to enable the user to use both LibA and LibB by merging the the "LibShared" libraries?

**Comment by marek-safar** [comment]
I'm not sure what you are asking exactly but illink is not doing any assemblies bundling. There are different tools doing that like https://github.com/dotnet/ILMerge which you could run before you run illink.

**Comment by ivan-prodanov** [comment]
@marek-safar Thanks for the help! I'm asking if merging is possible on a shared library that is used by two distinct libraries that have stripped off different IL parts of the shared library using illink. If a project is using these two shared libraries, can ILMerge be used in that case merge the different IL of the shared library into one assembly so both libraries can operate correctly with the merged result?

**Comment by marek-safar** [comment]
I see what you mean now. We don't support such scenario and I cannot think how we easily could without introducing some temporary new data format to carry the data. There are workarounds if you would be fine with the shared library not to be trimmed at all but I think ILMerge would fail if you passed on input two different copies of the same assembly. However, it should not be hard to write a simple tool which merged two copies of the same assembly if you know they have the same origin.

**Comment by vitek-karas** [comment]
I guess this is the scenario of multiple executables, one shared, self-contained framework, right?
Linker could in theory do this - but the SDK can't do this right now - related to this topic: https://github.com/dotnet/sdk/pull/14488

Linker might be able to take the two executables as two entry points (`-a`) and then the framework and link it all together - in which case it would correctly "merge" the dependencies from both executables over the same shared assemblies.

**Comment by ivan-prodanov** [comment]
@vitek-karas Not multiple executables, no. I'm working on a packaging tool that allows a user to package a class library and its dependencies to be used by mono wasm (from dotnet/runtime/mono). Once packaged, it could be plugged in any front end using npm. So far I was seeing trimming using ILLink being done at package time (because it's time consuming), ultimately this means that if a user is using two packages that share the same dependency, but trimmed in different ways, that the dependency could be merged to allow both packages to function properly at runtime after everything is loaded by mono.wasm.

**Comment by vitek-karas** [comment]
If this is going to be used from Blazor apps, those always run trimming during publish, so the performance savings by running trimming before hand on select packages will be probably rather small.

If this is for a different app model, then I can't really comment.

**Comment by ivan-prodanov** [comment]
Thanks for the support, everyone. I'm closing this as all my questions were answered.
