### ISSUE TITLE
warning IL2025: Duplicate preserve of 'System.Runtime.CompilerServices.AsyncIteratorMethodBuilder.get_ObjectIdForDebugger()'

### ISSUE THREAD

**Issue by eerhardt** [mono/linker#1718]
Publishing a trimmed application that references [`Microsoft.Bcl.AsyncInterfaces`](https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/) causes an ILLink warning that is not fixable by the end-user.

### Repro

```
❯ dotnet publish -r win-x64 -p:PublishTrimmed=true -p:TrimMode=link /bl
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\5.0.101\MSBuild.dll -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\5.0.101\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\5.0.101\dotnet.dll -maxcpucount -property:RuntimeIdentifier=win-x64 -p:PublishTrimmed=true -p:TrimMode=link -restore -target:Publish -verbosity:m /bl .\ConsoleApp1.sln
  Determining projects to restore...
  Restored F:\DotNetTest\LinkerBugRepro\ClassLibrary1\ClassLibrary1.csproj (in 213 ms).
  Restored F:\DotNetTest\LinkerBugRepro\ConsoleApp1\ConsoleApp1.csproj (in 213 ms).
  ClassLibrary1 -> F:\DotNetTest\LinkerBugRepro\ClassLibrary1\bin\Debug\netstandard2.0\win-x64\ClassLibrary1.dll
  ClassLibrary1 -> F:\DotNetTest\LinkerBugRepro\ClassLibrary1\bin\Debug\netstandard2.0\win-x64\publish\
  ClassLibrary1 -> F:\DotNetTest\LinkerBugRepro\ClassLibrary1\bin\Debug\netstandard2.0\ClassLibrary1.dll
  ConsoleApp1 -> F:\DotNetTest\LinkerBugRepro\ConsoleApp1\bin\Debug\net5.0\win-x64\ConsoleApp1.dll
resource System.Private.CoreLib.xml in System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e : warning IL2025: Duplicate preserve of 'System.Runtime.CompilerServices.AsyncIteratorMethodBuilder.get_ObjectIdForDebugger()' [F:\DotNetTest\LinkerBugRepro\ConsoleApp1\ConsoleApp1.csproj]
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  ConsoleApp1 -> F:\DotNetTest\LinkerBugRepro\ConsoleApp1\bin\Debug\net5.0\win-x64\publish\
```

Publish the attached app below using the above command.

[LinkerBugRepro.zip](https://github.com/mono/linker/files/5759184/LinkerBugRepro.zip)

### Notes

It appears the reason this warning happens is because the ILLinker command line looks like:

```
-a "C:\Users\eerhardt\.nuget\packages\microsoft.bcl.asyncinterfaces\5.0.0\lib\netstandard2.1\Microsoft.Bcl.AsyncInterfaces.dll"
-reference "C:\Users\eerhardt\.nuget\packages\microsoft.bcl.asyncinterfaces\5.0.0\lib\netstandard2.1\Microsoft.Bcl.AsyncInterfaces.dll"
-p copy "Microsoft.Bcl.AsyncInterfaces"
```

Which tells the ILLinker to preserve everything in that assembly. The ILLinker goes through all the Types in that assembly (including TypeForwardedTo types, which the `AsyncIteratorMethodBuilder` type is forwarded to System.Private.CoreLib) and "marks" them. Then later, the ILLinker goes through the XML descriptor file in System.Private.CoreLib, and sees this entry:

https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Private.CoreLib/src/ILLink/ILLink.Descriptors.Shared.xml#L35-L37

And then this line of code raises the warning:

https://github.com/mono/linker/blob/e68a1c586b5b5174e21e3f0d4b00322c547e4c3d/src/linker/Linker.Steps/ResolveFromXmlStep.cs#L203-L206

**Comment by vitek-karas** [comment]
SDK/linker interactions have changed quite a bit, and now this works without any warnings.
