### ISSUE TITLE
Roslyn analyzers need to register necessary MSBuild properties with the compiler

### ISSUE THREAD

**Issue by agocke** [mono/linker#1745]
See https://github.com/dotnet/roslyn-analyzers/blob/4ce9cd5efe21ab9e0eabfd4eb3565cd2dde76b35/src/Tools/GenerateDocumentationAndConfigFiles/Program.cs#L1457

Basically, only properties which are marked `CompilerVisibleProperty` will get copied over. We can create a `.props` file for our NuGet package to automatically register all the MSBuild properties we need.

**Comment by tlakollo** [comment]
Closing via #1767
