### ISSUE TITLE
`IsDynamicCodeCompiled` path no longer being trimmed in 6.0.100-alpha.1.21062.9

### ISSUE THREAD

**Issue by tannergooding** [mono/linker#1747]
### Repro
1. Install v6.0.100-alpha.1.21062.9 of the SDK from dotnet/installer.
2. Create a new blazorwasm project: `dotnet new blazorwasm`
3. Publish the project with trimming: `dotnet publish -c Release` (optionally dump the dependencies with `/p:_TrimmerDumpDependencies=true`
4. Examine the `Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider` method in `Microsoft.Extensions.DependencyInjection.dll`
5. See that the call to `RuntimeFeature.IsDynamicCodeCompiled` still exists as does the path that invokes `new DynamicServiceProviderEngine(services)`

### Expected behavior

`RuntimeFeature.IsDynamicCodeCompiled` should be `false` (it is in the `S.P.Corelib` assembly) and the code path handling `DynamicServiceProviderEngine` should have been trimmed.

### Actual Behavior

It is not trimmed which is causing `System.Reflection.Emit` to not be trimmed.

**Comment by tannergooding** [comment]
This does not repro on `6.0.100-alpha.1.21057.4`: https://github.com/mono/linker/commit/83ea45b8f4ffcfe5e1d15c1b42d0d1a003865864
Repro: `6.0.100-alpha.1.21062.9` is https://github.com/mono/linker/commit/7a095faf3925689f2a3450da1a76fdd79a070de9

There are 6 commits between these: https://github.com/mono/linker/compare/83ea45b...7a095fa

**Comment by MichalStrehovsky** [comment]
Cc @vitek-karas since #1734 is the most obvious suspect in that range.
