### ISSUE TITLE
Using linker for a solution

### ISSUE THREAD

**Issue by sherlock1982** [mono/linker#178]
Hi! I have a set of .NET Core projects which I output into same directory. I use self-contained deployment and equalize package versions with an extra script. 

Is there a way I can benefit from using linker? Can I use it on a solution somehow?

Maybe it can have an option to exclude only completely unused assemblies.

**Comment by sherlock1982** [comment]
Ah that's interesting. So I can run it after I publish all executables to one directory and specify top level assemblies. Than it can minimize output for me.

Can I somehow run it from a command line after I build a solution ? Or from a phony project file?

**Comment by erozenfeld** [comment]
Yes, you can do that: https://github.com/dotnet/core/blob/master/samples/linker-instructions-advanced.md#for-more-control
