### ISSUE TITLE
Hitting Debug.Assert in `MarkTypeWithDebuggerDisplayAttribute`

### ISSUE THREAD

**Issue by mrvoorhe** [mono/linker#1784]
Someone on my team is running into this `Debug.Assert` while trying to debug something unrelated.

https://github.com/Unity-Technologies/linker/blob/b89f103fc9d8b5ecf78912cc4238f24a4d3cf352/src/linker/Linker.Steps/MarkStep.cs#L1743

Either something in the code needs to be fixed or the Debug.Assert doesn't need to be there

**Comment by sbomer** [comment]
Sorry this is still causing trouble - the assert was removed in https://github.com/mono/linker/pull/1629.

**Comment by mrvoorhe** [comment]
My bad.  I thought I went to monolinker/master but I was still looking at our fork.
