### ISSUE TITLE
Update mono/linker to support .NET 6

### ISSUE THREAD

**Issue by vitek-karas** [mono/linker#1785]
Currently all of the mono/linker is built against .NET 5 (TFM=`net5.0`). In order to be able to test some of the new reflection APIs in .NET 6, at least the test projects will need to build against .NET 6 (TFM=`net6.0`).

This will require new SDK and potentially some Arcade changes.

**Comment by vitek-karas** [comment]
We should only update to P1 once it's available. For now update to a random build is in https://github.com/vitek-karas/linker/tree/UpgradeTestsToNET6. It works with exception of one ILLink task test.

**Comment by marek-safar** [comment]
SDK dependency was updated to .NET6 P0, could you push your changes?

**Comment by vitek-karas** [comment]
Fixed by https://github.com/mono/linker/pull/1891
