### ISSUE TITLE
RequiresAssemblyFilesAttribute error code and messages

### ISSUE THREAD

**Issue by MichalStrehovsky** [mono/linker#1786]
I had a look at #1722 because I wanted to steal stuff from it for NativeAOT, but it's missing some important things.

* The error message is missing:

https://github.com/mono/linker/blob/92b9b51bb8548320e40fc432efcb395156ad1445/src/ILLink.RoslynAnalyzer/Resources.resx#L138-L142

* It claimed IL3002 error code but there's no documentation for it in the [master error code registry](https://github.com/mono/linker/blob/master/docs/error-codes.md).

**Comment by agocke** [comment]
@tlakollo Can you pick this up? I think writing a resource message is the highest priority. Right now the analyzer doesn't really print anything.

**Comment by tlakollo** [comment]
So far I created a PR that includes a default message and the arguments.
Seems like other error codes have a help link uri like in https://github.com/mono/linker/pull/1736, not sure if we need one for IL3002
Also not sure if we are not including the IL3XXX codes in the master error code registry in order to not confuse with other linker codes and patterns.

**Comment by mateoatr** [comment]
> Also not sure if we are not including the IL3XXX codes in the master error code registry in order to not confuse with other linker codes and patterns

We should at least link to [IL3000](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/il3000) and IL3001 (https://github.com/mono/linker/issues/1498#issuecomment-695054111). Also, I think we should create a similar docs page for IL3002 once we decide on a specific message.

**Comment by MichalStrehovsky** [comment]
If we expect that illink will eventually also have analysis for single-file friendliness, this is a illink error code like any other. The user doesn't care what tool produced the warning if the fix is the same. We want the codes to be same so that suppressions work the same way (if I suppress the warning in the analyzer, I really don't want yet another warning for the same problem from illink).

If we don't expect this functionality to ever converge with illink, we should have chosen a different prefix.

**Comment by agocke** [comment]
> If we don't expect this functionality to ever converge with illink, we should have chosen a different prefix.

I'm not sure exactly what tool will perform the analysis, but I do assume that the linker or something else will produce single-file analysis as well.

**Comment by tlakollo** [comment]
Closing via #1790
