### ISSUE TITLE
Expressions of the form `switch {` cause dotnet-format to fail

### ISSUE THREAD

**Issue by mateoatr** [mono/linker#1796]
Whenever there's a switch expression with a `{` in the same line (`var switch {`), dotnet-format reports whitespace formatting errors. This makes it hard to understand what's wrong. For an example, see here: https://dev.azure.com/dnceng/public/_build/results?buildId=971006&view=logs&j=ed7ee28b-73cd-526d-4740-b3f2e2c1c6bb&t=e71a6653-5b93-50ae-6545-9f859da4990d&l=365.

**Comment by marek-safar** [comment]
I don't think we can do much about it here. Please report the issue to dotnet/format

**Comment by MichalStrehovsky** [comment]
> I don't think we can do much about it here. Please report the issue to dotnet/format

We could adopt formatting rules that the rest of the .NET world uses and are well tested in dotnet/format 😛

**Comment by mateoatr** [comment]
Opened https://github.com/dotnet/format/issues/948
