### ISSUE TITLE
Simplify copy action behavior

### ISSUE THREAD

**Issue by sbomer** [mono/linker#1800]
The linker accepts copy ~~and save~~ as actions on the command line, which has the behavior that input assemblies which are part of the reference closure of the roots get fully preserved. This requires loading all references, including unused ones. We should:
- Get rid of copy/~~save~~ *default* actions
  - I am not aware of scenarios where they are needed (it would effectively prevent linking if they were used)
- Unify the "copy"/"root" options
  - "copy" used to affect the output only, but it has changed to mean something similar to "-a Assembly.dll all"
  - The SDK should then change to pass a single option instead of marking `IsTrimmable="false"` assemblies as copy + root
  - ~~Open question: can we also get rid of "save"?~~ 
Edit: I forgot that https://github.com/mono/linker/pull/1725 already removed `save` as a command-line option. 
- Ensure that the unified behavior behaves the same as an attribute opt-in
  - It should preserve assemblies even if they were not part of the reference closure

**Comment by mrvoorhe** [comment]
@sbomer I don't entire follow what this issue is about. Is `AssemblyAction.Copy` going to be removed or have it's behavior changed?  Unity depends on `AssemblyAction.Copy` today.  That's not to say we can't change, `AssemblyAction.Copy` does lead to some quirks, I'd just like to understand if this issue means there are plans to change/remove `AssemblyAction.Copy`.

**Comment by sbomer** [comment]
@mrvoorhe  I think most importantly, we want to change the behavior so that:
- `copy` will automatically root an assembly (today, it only roots assemblies that are part of the reference closure)

Otherwise the same quirks (for example copy assemblies being rewritten due to removed type forwarders) would remain. We might then consider renaming it or merging it with the `-a` command-line option, but the important piece is the behavior change.

Would that be reasonable behavior for unity? For the .NET SDK it doesn't make a big difference because we only pass "copy" in conjunction with "-a" by default, though there could technically be edge cases where users specify "copy" for an unreferenced assembly (which would cause it to be kept after the change).

Next, I am also suggesting we:
- Stop supporting `-u copy` and `-c copy`

These are more options that are unused by the .NET SDK and unnecessarily complicate some cases in the linker.

It would be good to know how Unity uses `copy`.

**Comment by mrvoorhe** [comment]
> copy will automatically root an assembly (today, it only roots assemblies that are part of the reference closure)

This seems OK.

> Stop supporting -u copy and -c copy

This seems OK if the internal support for `AssemblyAction.Copy` is still in place.

From a command line perspective, we don't use -a, -u, or -c.  We have our own `--include-unity-root-assembly` argument that we use.  Our command line argument then uses `ResolveFromAssemblyStep` (looks like this has been renamed) and `LinkContext.SetAction` to setup the link behavior for various assemblies.

Our default behavior today is to assign `AssemblyAction.Copy` to a subset of the users assemblies.  Everything else gets assigned `AssemblyAction.Link`.  That said, our users have a fair number of problems with reflection & serialization that they don't realize is problematic for code stripping.   One idea floating around is to assign `AssemblyAction.Copy` to all users assemblies and only link the class libraries and Unity assemblies by default.  So we may expand our usage of `AssemblyAction.Copy` in the future.

**Comment by sbomer** [comment]
Thanks! That's pretty much how the .NET SDK uses the option too - we already assign `AssemblyAction.Copy` to user assemblies by default - so I don't expect this to cause any problems.

**Comment by vitek-karas** [comment]
@sbomer has this been solve already with the recent changes?

**Comment by sbomer** [comment]
The functional change is done:
> copy will automatically root an assembly

We could still simplify the command-line:
1. Unify `--action copy <asm>` with `-a <asm> all` (they do the same thing as far as I can tell)
2. Stop supporting `--trim-mode copy` (global action for trimmable assemblies - doesn't seem useful as this would prevent trimming)

But those seem less important (and 1. would take more thought to define how other root modes/actions work). I think we can close it.
