### ISSUE TITLE
Investigate warning behavior for copyused/link TrimMode

### ISSUE THREAD

**Issue by sbomer** [mono/linker#1836]
We don't remove unused branches from `copyused` assemblies, leading to differences in the warning output between copyused/link. Generally speaking, the expectation is that `copyused` keeps more code and doesn't eliminate branches, so it should produce more warnings. However, some of the warning behavior across copyused/link is not understood - these need to be investigated and possibly fixed:
- Why don't we see warnings from `StartupHookProvider.CallStartupHook` (which has `RequiresUnreferencedCode`) when TrimMode is `copyused`?
  - The expectation is that it would behave the same as the ResourceManager case (details below).
- Why does TrimMode `link` produce the following extra warnings compared to `copyused`?
```
ILLink : Trim analysis warning IL2026: System.ComponentModel.Design.DesigntimeLicenseContextSerializer.Deserialize(Stream,String,RuntimeLicenseContext,...
ILLink : Trim analysis warning IL2067: System.ComponentModel.LicenseManager.CreateWithContext(Type,LicenseContext,Object[]...
ILLink : Trim analysis warning IL2072: System.ComponentModel.LicenseManager.ValidateInternalRecursive(LicenseContext,Type,Object,Boolean,License&,String&...
```

See @tlakollo 's WIP change which adds a `link` warning testcase: https://github.com/dotnet/sdk/pull/15837/files

<hr />

More details on a case that works as expected (a call from from `CreateResourceSet` to a method with `RequiresUnreferencedCode`):

- When the feature switch `System.Resources.ResourceManager.AllowCustomResourceTypes` is `false`, substitutions can eliminate a branch from `CreateResourceSet` that [calls](https://github.com/dotnet/runtime/blob/0026a202ab4087d237f6be8824dff322d3a7d6be/src/libraries/System.Private.CoreLib/src/System/Resources/ManifestBasedResourceGroveler.cs#L238) a method which has `RequiresUnreferencedCode`.
- With the default `<TrimMode>copyused</TrimMode>`, the linker doesn't eliminate this branch, and emits a warning about this call inside `CreateResourceSet` (see https://github.com/dotnet/sdk/pull/15764#discussion_r574148478):
```
ILLink : Trim analysis warning IL2026: System.Resources.ManifestBasedResourceGroveler.CreateResourceSet(Stream,Assembly...
```
- The warning goes away with `<TrimMode>link</TrimMode>` because this will allow us to rewrite corelib to eliminate the offending branch. This is expected.

@eerhardt @vitek-karas

**Comment by tlakollo** [comment]
In the case of CallStartupHook we dont see a warning because there is an Unconditional Suppress attribute https://github.com/dotnet/runtime/blob/master/src/coreclr/System.Private.CoreLib/src/ILLink/ILLink.Suppressions.LibraryBuild.xml

**Comment by eerhardt** [comment]
@tlakollo - that suppression xml file is only used when building the dotnet/runtime. It isn’t used while trimming an application.

**Comment by mateoatr** [comment]
It looks like the `System.Private.CoreLib` descriptors file is not properly named (either that, or the linker should stop enforcing the need of descriptor files to be named `ILLink.Descriptors.xml`) https://github.com/mono/linker/blob/2cb420dbabb4ec86d41a1b431696e58f45f031cd/src/linker/Linker/EmbeddedXmlInfo.cs#L110 

When using ildasm on the SPCL, I see the file named as `System.Private.CoreLib.xml`, so we don't root `StartupHookProvider` (and other members not called nor referenced by anything in the managed side), which is only called by unmanaged code: https://github.com/dotnet/runtime/blob/bc544bd171674762d8ba8694f55df15465d6e3b0/src/coreclr/vm/assembly.cpp#L1639

If we actually process this descriptors file, I get the following warnings (no feature switches, no nowarns):

```
ILLink: Trim analysis warning IL2026: System.ComponentModel.Design.DesigntimeLicenseContextSerializer.Deserialize(Stream,String,RuntimeLicenseContext): Using method 'System.Runtime.Serialization.IFormatter.Deserialize(Stream)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. BinaryFormatter serialization is not trim compatible because the Type of objects being processed cannot be statically discovered..
ILLink: Trim analysis warning IL2067: System.ComponentModel.LicenseManager.CreateWithContext(Type,LicenseContext,Object[]): '#0' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in call to 'System.Object System.Activator::CreateInstance(System.Type,System.Object[])'. The parameter 'type' of method 'System.ComponentModel.LicenseManager.CreateWithContext(Type,LicenseContext,Object[])' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
ILLink: Trim analysis warning IL2072: System.ComponentModel.LicenseManager.ValidateInternalRecursive(LicenseContext,Type,Object,Boolean,License&,String&): '#0' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in call to 'System.Object System.Activator::CreateInstance(System.Type)'. The return value of method 'System.ComponentModel.LicenseProviderAttribute.LicenseProvider.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
ILLink: Trim analysis warning IL2057: System.ComponentModel.LicenseProviderAttribute.LicenseProvider.get: Unrecognized value passed to the parameter 'typeName' of method 'System.Type.GetType(String)'. It's not possible to guarantee the availability of the target type.
ILLink: Trim analysis warning IL2072: System.Diagnostics.Tracing.EventSource.EnsureDescriptorsInitialized(): 'eventSourceType' argument does not satisfy 'All' in call to 'System.Diagnostics.Tracing.EventSource.CreateManifestAndDescriptors(Type,String,EventSource,EventManifestOptions)'. The return value of method 'System.Object.GetType()' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
ILLink: Trim analysis warning IL2026: System.Resources.ManifestBasedResourceGroveler.CreateResourceSet(Stream,Assembly): Using method 'System.Resources.ManifestBasedResourceGroveler.InternalGetResourceSetFromSerializedData(Stream,String,String,ResourceManager.ResourceManagerMediator)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. The CustomResourceTypesSupport feature switch has been enabled for this app which is being trimmed. Custom readers as well as custom objects on the resources file are not observable by the trimmer and so required assemblies, types and members may be removed..
ILLink: Trim analysis warning IL2026: System.StartupHookProvider.ProcessStartupHooks(): Using method 'System.StartupHookProvider.CallStartupHook(StartupHookProvider.StartupHookNameOrPath)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. The StartupHookSupport feature switch has been enabled for this app which is being trimmed. Startup hook code is not observable by the trimmer and so required assemblies, types and members may be removed.
ILLink: Trim analysis warning IL2070: System.Diagnostics.Tracing.TypeAnalysis.TypeAnalysis(Type,EventDataAttribute,List<Type>): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Type.GetProperties()'. The parameter 'dataType' of method 'System.Diagnostics.Tracing.TypeAnalysis.TypeAnalysis(Type,EventDataAttribute,List<Type>)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
```

We actually see the warnings when using `link` action since it'll make the linker process all different substitution files, thus processing https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/ILLink/ILLink.Substitutions.Shared.xml and marking `System.StartupHookProvider` (similarly with other warnings).

I just opened a PR in dotnet/runtime to fix the descriptors filename: https://github.com/dotnet/runtime/pull/48430

**Comment by sbomer** [comment]
Thanks for the help investigating!
