### ISSUE TITLE
Linker is warning for calling GetProperty on BaseType of DynamicallyAccessedMemberTypes.All

### ISSUE THREAD

**Issue by eerhardt** [mono/linker#1882]
We have some code in `dotnet/runtime` which walks up an inheritance hierarchy looking for a property:

https://github.com/dotnet/runtime/blob/3973fc6b785a6adb24453b88681bde2ac83f370c/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectPropertyDescriptor.cs#L407-L410

In my local changes I have:

```C#
for (Type t = _componentClass.BaseType; t != null && t != typeof(object); t = t.BaseType)
{
    BindingFlags bindingFlags = BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.Instance;
    PropertyInfo p = t.GetProperty(name, bindingFlags, binder: null, PropertyType, Type.EmptyTypes, null);
```

where `_componentClass` is annotated with `[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]`.

However, the linker is issuing the following warning:

```
ReflectPropertyDescriptor.cs(410,29): Trim analysis warning IL2075: System.ComponentModel.ReflectPropertyDescriptor.SetMethodValue.get: 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Type.GetProperty(String,BindingFlags,Binder,Type,Type[],ParameterModifier[])'. The return value of method 'System.Type.BaseType.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
```

where line 410 is the `PropertyInfo p = t.GetProperty(name, bindingFlags, binder: null, PropertyType, Type.EmptyTypes, null);` line.

Since I've annotated the type with `All`, I'd expect the linker not to warn in this case.

cc @vitek-karas

**Comment by vitek-karas** [comment]
This is basically a dupe of https://github.com/mono/linker/issues/1758. I'll leave this one opened as an "example" for the more general issue.

**Comment by vitek-karas** [comment]
This should be fixed now. @eerhardt can you please see (once linker updates in runtime) if it resolved the warning above?

**Comment by eerhardt** [comment]
> @eerhardt can you please see (once linker updates in runtime) if it resolved the warning above?

I was able to remove all suppressions with this linker issue number attached to them. So I believe we can close this now.

One set that I was unable to remove is because of https://github.com/mono/linker/issues/1731 - `GetInterfaces()`, but that issue can be tracked there.
