### ISSUE TITLE
Annotating property indexers causes the linker to treat the key (index) to have the annotations too.

### ISSUE THREAD

**Issue by joperezr** [mono/linker#1902]
Consider this code:

```c#
public class MyTypeDictionary
{
  [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)]
  public Type this[string key] { get; set; }
}
```

With the annotation slapped to the indexer, what you really want is for the getter return value, as well as for the setter param value to get annotated. In reality what happens is that the whole property gets annotated and so the linker will treat the setter as having two params `(string key, Type value)` both of which it will consider as annotated meaning we would need to preserve their constructors. Problem being that if you then have some consuming code like:

```c#
MyTypeDictionary dict = new MyTypeDictionary();
dict[myStringParam] = typeof(StringBuilder);
```

to throw a linker warning since the key parameter (the string) is not annotated. For now, the workaround is to annotate the getter and setter individually like:

```c#
public Type? this[string key]
{
    [return: DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)]
    get;
    [param: DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)]
    set;
}
```

The code above will produce the following IL:

```
.method public hidebysig specialname 
    instance void set_Item (
        string key,
        class [System.Runtime]System.Type 'value'
    ) cil managed 
{
    .param [2]
        .custom instance void [System.Runtime]System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembersAttribute::.ctor(valuetype [System.Runtime]System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes) = (
            01 00 01 00 00 00 00 00
        )
    // Method begins at RVA 0x12aa1a
    // Code size 15 (0xf)
```

which shows how only the value parameter gets annotated so that the linker will only throw warnings if Type param is not annotated.

**Comment by joperezr** [comment]
Some context on how this was found: https://github.com/dotnet/runtime/pull/49413#discussion_r593556500

cc: @eerhardt

**Comment by marek-safar** [comment]
I'm not sure what better behaviour should look like, right now the linker does exactly what you told him to do. Should linker warn when you add `DynamicallyAccessedMembers` to void members?

/cc @vitek-karas @MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
Illink is propagating the annotation to the first parameter of the setter - in the case of an indexer, it's the wrong parameter. It should instead propagate to the last parameter of the setter.

I think the fix is to replace this line:

https://github.com/mono/linker/blob/e06f9dc61a3dc2cad0f1138638e7a34c6eb6e5cc/src/linker/Linker.Dataflow/FlowAnnotations.cs#L275

with

```csharp
 paramAnnotations[setMethod.Parameters.Count - 1] = annotation; 
```

**Comment by vitek-karas** [comment]
@tlakollo can you please fix this? It's mostly just about adding a test.

**Comment by tlakollo** [comment]
It will take more time than I expected, the Sweepstep is deleting the property accessors because they were not marked. SO Im investigating what in the markstep is wrong.
