### ISSUE TITLE
LinkAttributes doesn't support custom attribute overloading

### ISSUE THREAD

**Issue by tlakollo** [mono/linker#1915]
It's not possible to insert certain overloads of DynamicDependency using the LinkAttributes file.
For example:
```C#
public class ReferencedType {
  // Attribute trying to be inserted in the code via xml
  // [DynamicDependency (DynamicallyAccessedMemberTypes.All, NonUsedType)]
  public static void Main () {}
}

public class NonUsedType {
  public static void PleasePreserveThisMethod () {}
}
```
The main problem is that the xml only supports to write something like the following:
```XML
<linker>
  <assembly fullname="SomeAssembly">
    <type name="ReferencedType">
      <method signature="System.Void Main()">
        <attribute fullname="System.Diagnostics.CodeAnalysis.DynamicDependency">
          <argument>All</argument>
          <argument>NonUsedType</argument>
        </attribute>
      </method>
    </type>
  </assembly>
</linker>
```
The previous code assumes that argument one is of type MemberTypes. In practice, the linker will take the first constructor that matches the number of arguments, in this case, it will take the overload of DynamicDependency that takes as the first argument a string and the second argument a type.
```C#
// This is the constructor the linker finds just by searching a constructor with 2 arguments
public DynamicDependencyAttribute(string memberSignature, Type type);

public DynamicDependencyAttribute(DynamicallyAccessedMemberTypes memberTypes, Type type);
```
We should have a way to declare the type of argument to override the default behavior of the linker.

**Comment by marek-safar** [comment]
Funnily I was looking into fixing this last week and I'm halfway through on PR as I hit that in other scenarios as well. It will be breaking change for certain use-cases but I think the current behaviour of choosing an overload nondeterministically is wrong.
