### ISSUE TITLE
Reenable ILLink.RoslynAnalyzer.Tests.RequiresCapability test

### ISSUE THREAD

**Issue by marek-safar** [mono/linker#1918]
I had to disable the ILLink.RoslynAnalyzer.Tests.RequiresCapability test because it caused random failures on CI. One example can be seen at https://github.com/mono/linker/runs/2183040383

It seems like the test data enumeration is not deterministic and also returns very different results on different platforms which is strange.

**Comment by agocke** [comment]
Fixed by https://github.com/mono/linker/pull/2029
