### ISSUE TITLE
IL Trimming should produce a warning for WPF and Winforms in .NET 6

### ISSUE THREAD

**Issue by agocke** [mono/linker#1933]
Neither framework will be safe for trimming in .NET 6. Rather than show all the warnings, which won't be helpful, we should have one prominent warning that IL trimming is not supported for these application types.

We may also want to either warn about COM being disabled by default in WinForms, or enable it.

**Comment by marek-safar** [comment]
Why do you think this should be handled specially by the linker and not by SDK?

**Comment by agocke** [comment]
This is probably better done in the SDK -- I just didn't think about it before filing the issue.

**Comment by agocke** [comment]
Duping with https://github.com/dotnet/sdk/issues/16716
