### ISSUE TITLE
Sharing state between custom steps

### ISSUE THREAD

**Issue by sbomer** [mono/linker#1953]
It should be possible to use multiple custom steps with shared state. The way xamarin-android does this is:
1. [Register](https://github.com/xamarin/xamarin-android/blob/681887ebdbd192ce7ce1cd02221d4939599ba762/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets#L61) a single custom step ([SetupStep](https://github.com/xamarin/xamarin-android/blob/main/src/Microsoft.Android.Sdk.ILLink/SetupStep.cs)) via --custom-step
2. SetupStep creates multiple new steps, some with shared [state](https://github.com/xamarin/xamarin-android/blob/d21a42c9e328236cc4fd2f28eecc563e9c48dead/src/Microsoft.Android.Sdk.ILLink/SetupStep.cs#L40)
3. SetupStep [uses](https://github.com/xamarin/xamarin-android/blob/d21a42c9e328236cc4fd2f28eecc563e9c48dead/src/Microsoft.Android.Sdk.ILLink/SetupStep.cs#L20) reflection to add these steps to the linker pipeline

We should provide a way to share state that doesn't require such workarounds. Some options are:
- Make Pipeline available in the ref assembly so adding steps doesn't require reflection
- Design a new api with the same purpose, and make that available in the ref assembly
- Require shared state to be static on one of the custom steps, and fix https://github.com/mono/linker/issues/1314

If we disallow shared state, then xamarin-android could work around it by grouping steps with shared state together, but this isn't the best for code organization, and means that these steps will run in order, without other steps in-between (limiting what custom steps can do without more workarounds).

**Comment by marek-safar** [comment]
The existing state sharing methods available to custom steps are

https://github.com/mono/linker/blob/main/src/linker/ref/Linker/Annotations.cs#L34-L35
https://github.com/mono/linker/blob/main/src/linker/ref/Linker/LinkContext.cs#L21-L22

We could extend existing state sharing APIs if there is a use case for it but I'm not sure this is the good one. The code seems to be sharing a result of [Resolve](https://github.com/xamarin/java.interop/blob/a3de91efdaec04b3927b755a07018e8d26cfdc71/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionCache.cs#L18) call which I'm not sure it's worth it. If you think it's then we could expose it to everyone if we think it's valuable or you could change the code to do something like.

```c#
public TypeDefinition ResolveWithCache (TypeReference typeReference)
{
	  var cached = context.Annotations.GetCustomAnnotation (this, typereference);
	  if (cached == null) {
		  cached = typeReference.Resolve ();
		  context.Annotations.SetCustomAnnotation (this, typereference, cached);
	  }
	  
	  return (TypeDefinition) cached;
}
```
