### ISSUE TITLE
COM warnings from generated descriptors 

### ISSUE THREAD

**Issue by sbomer** [mono/linker#1973]
On linux the linker produces warnings like the following: resource ILLink.Descriptors.xml in System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e : warning IL2008: Could not resolve type 'System.StubHelpers.MngdSafeArrayMarshaler' [/home/sven/tmp/trimmed/trimmed.csproj]
 
I think they are coming from the runtime-generated descriptors which reference COM, even though COM is only enabled on windows. We may want to take DefineConstants into account when parsing header files in https://github.com/mono/linker/blob/main/src/ILLink.Tasks/CreateRuntimeRootDescriptorFile.cs.

/cc @LakshanF @vitek-karas

**Comment by vitek-karas** [comment]
For Preview 4 we suppressed these via https://github.com/dotnet/sdk/pull/16979.
After Preview 4 we need to fix this and remove the suppressions.

**Comment by vitek-karas** [comment]
This has been fixed both in runtime and SDK - there should be no implicit suppressions for .NET 6 apps anymore.
