### ISSUE TITLE
Adjust trim UI in VS Publish

### ISSUE THREAD

**Issue by agocke** [mono/linker#2011]
There are a couple changes we should make for 6.0:

- Remove the preview flag
- Change wording away from "trim unused assemblies"
- See if we can remove the checkbox for the net5.0-windows TFM
- Have the publish output respect verbosity configuration from VS settings

The last one isn't related to the checkbox, but when testing it out I found out that the verbosity is always set to normal (and you can't change it). This causes a flood of output that covers up linker warnings, which we should try our best to avoid.

**Comment by AngelosP** [comment]
Hello there :) Looks like we basically have:

1. **String change: this will take care of the "preview" flag and the existing wording.** Do we have another suggestion to consider here? We aim to keep this type of vocabular consistent between CLI and VS.
2. **Visibility change based on TFM: hide the checkbox completely based on certain TFMs.** Why do we want to do that?
3. **A way to configure publish output verbosity (or at least consider changing the default):** Do we have another default to suggest?

**Comment by agocke** [comment]
@AngelosP Thanks for the quick reply!

1. In the CLI this is just called "PublishTrimmed". Maybe we should just say "trim unused code" instead of "trim unused assemblies"? Previously we stopped at the assembly boundary, now we trim unused members by-default.
2. Trimming isn't supported for WinForms or WPF and is likely to result in a broken app. If it's simple enough, checking if the UseWPF or UseWindowsForms properties are set to true is how we produce the warning, and would be great for disabling the checkbox.
3. The default verbosity for the CLI is `minimal` and that seems to produce a good experience. I believe the old VS output default was normal but mine appears to be set to minimal:
![image](https://user-images.githubusercontent.com/515774/116925661-4dd11600-ac0e-11eb-9746-949901ed2c4e.png)
I can't remember if I did that or if that's a new default. Either way, since warnings from `publish` don't appear in the error list, I think `minimal` would be better, since it's more important to be able to quickly read the output window.

**Comment by AngelosP** [comment]
Sounds good! I've logged a bug for this work: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1323204

**Comment by vijayrkn** [comment]
@agocke - To finalize the plan here: 
1. We will change the text from "Trim unused assemblies (in preview)" to "Trim unused code".
2. We will hide the checkbox for WinForms apps and WPF apps. This will be shown for ASP.NET Core apps (including Blazor) even though you mentioned that this is not fully supported.
3. We will only show this option for apps targeting .NET 6.0+ (this means we will start hiding the checkbox for previous versions).

The msbuild verbosity change is out of scope of this item (this is a msbuild VS wide change and has other implications). This should be handled separately. 

/cc @DamianEdwards and @danroth27 in case you have concerns with the plan for ASP.NET Core.

**Comment by agocke** [comment]
(1) and (2) sound great, thanks. (3) sounds unnecessary -- I wouldn't necessarily want to remove functionality for earlier frameworks, even if it was in Preview.

If you have another suggestion on the verbosity change, I'd be interested. Given the importance of trim diagnostics to a successful experience, I think it's very important that we have an answer here.

**Comment by vijayrkn** [comment]
For (3), we would like to keep VS versions to only support GA functionalities. Since the feature is at preview level for all down level versions (.NET Core 3.1 to .NET 6.0), I don't see why you want the preview functionality to show up for old apps in new versions of VS. 

Users would continue to see the preview flag in existing versions (Dev16). The new change is Dev17+

**Comment by agocke** [comment]
>  Since the feature is at preview level for all down level versions (.NET Core 3.1 to .NET 6.0), I don't see why you want the preview functionality to show up for old apps in new versions of VS.

Only because this would be a bit of a take-back, but I can see why we would want new VS versions to have a uniform feature set.

**Comment by vijayrkn** [comment]
Since this will be added to the next major version of VS, it should be okay to not support preview features for apps targeting older versions of runtime.

**Comment by agocke** [comment]
Agreed

**Comment by vijayrkn** [comment]
Regarding the verbosity question, VS publish does honor the msbuild verbosity set at the VS level. So, Unless I am mis-understanding something, there is no action required here. 

![image](https://user-images.githubusercontent.com/3981619/119054226-21dac200-b97c-11eb-9289-419e5da9fd12.png)

**Comment by agocke** [comment]
I just checked again, and it doesn't look like Minimal build verbosity. It certainly produces more output than a command-line publish.

Publish settings:

![image](https://user-images.githubusercontent.com/515774/119056579-c7436500-b97f-11eb-964f-2c0a7ea997f1.png)

Output window:
![image](https://user-images.githubusercontent.com/515774/119056558-bc88d000-b97f-11eb-819c-ce98951a7674.png)

**Comment by vijayrkn** [comment]
If you toggle the word wrap, it is just one additional line that is the difference between the two. It is not the "minimal" vs "normal" verbosity because normal adds a lot more output. I don't know why the corecompile target behaves differently between CLI & VS but that seems to be the only diff. 



![image](https://user-images.githubusercontent.com/3981619/119058585-84838c00-b983-11eb-825d-c38b7dfad731.png)

**Comment by agocke** [comment]
Word wrap is toggled for me (you can see the `csc` call in my output as well), but I think the illink invocation has newlines in its formatting. It looks like the same thing happens with crossgen2 if you set `ReadyToRun` to true.

We could track down where this formatting happens for each of the MSBuild tool tasks and try to remove line breaks, but it seems fragile.

**Comment by marek-safar** [comment]
> We will hide the checkbox for WinForms apps and WPF apps. This will be shown for ASP.NET Core apps (including Blazor) even though you mentioned that this is not fully supported.

Showing the checkbox for Blazor does not make much sense and if anyone would uncheck it would essentially break the publishing.

**Comment by agocke** [comment]
Oops, thanks @marek-safar, I forgot about that -- trimming is enabled by default for Blazor and can't really be disabled.

**Comment by vijayrkn** [comment]
When trimming is enabled (i.e when the user selects the option in the checkbox), we pass the following property to msbuild as part of publish - `<PublishTrimmed>True</PublishTrimmed>`. 

In the case of BlazorWASM, do you expect us to pass this property always during publish since trimming needs to be always enabled? or is this implicitly set for all BlazorWASM projects? 

Depending on the above, we can decide whether the checkbox needs to be shown (checked & disabled) or whether we need to hide it. If no additional property needs to be passed & this is the only valid scenario, I think we can safely hide it.

**Comment by marek-safar** [comment]
> In the case of BlazorWASM, do you expect us to pass this property always during publish since trimming needs to be always enabled?

I don't expect VS to pass the property as it's already set to true for the workload by default so it would have no effect.

**Comment by vijayrkn** [comment]
Sounds good. Thanks @marek-safar. We will hide the checkbox in that case for BlazorWASM projects.

**Comment by vijayrkn** [comment]
>We could track down where this formatting happens for each of the MSBuild tool tasks and try to remove line breaks, but it seems fragile.

https://github.com/mono/linker/blob/aaf4880139edc005a56284a85fafcf8a58f418d8/src/ILLink.Tasks/LinkTask.cs#L321

**Comment by agocke** [comment]
@vijayrkn Thanks, but I meant that we would have to do the same for the R2R task, and if any other team has a task which gets run during publish and does the same thing, we will have to do the same for them.

In other words, there's no good way to prevent an experience regression.

**Comment by vijayrkn** [comment]
@agocke - Agreed. The root cause here is that publish is trying to output more than what the CLI emits. Doesn't look like an msbuild verbosity issue but some tasks emitting more output that required/needed when `BuildingInsideVisualStudio` is set. 

Removing the newlines could reduce the impact of this in the interim if needed.

**Comment by agocke** [comment]
Thanks, we'll make that change for now

**Comment by vijayrkn** [comment]
Thanks! And I will add it my list to see why VS publish behaves _differently_.

**Comment by DamianEdwards** [comment]
I know there was some discussion about reducing the differences between build and publish, especially for the non-web workloads. Should we be looking at adding these options to the build properties pages too with that in mind? @richlander  

Also rather than the logic for showing or hiding the boxes in publish being in VS, could we not make it respect what's in the project (directly or via the SDK) already?

**Comment by vijayrkn** [comment]
Moving these options to the build properties page might need a broader discussion. 

Outside of trim, SingleFile & ReadyToRun might also have to move. Also, VS publish today supports building the project as portable but publishing as self-contained (VS runs a separate independent restore for the RID as a part of publish that does not interfere with the build restore). Is this scenario interesting in the new mode? 

![image](https://user-images.githubusercontent.com/3981619/119203273-844cc480-ba47-11eb-94d8-432fdd653654.png)

**Comment by richlander** [comment]
> I know there was some discussion about reducing the differences between build and publish

Yes. I think the plan is that the mobile/Xamarin workloads will established in .NET 6 exclusively around the `build` verb. In subsequent releases, we may (hopefully) orient the rest of the workloads the same way.

**Comment by agocke** [comment]
@vijayrkn One more thing we noticed -- it looks like the check boxes are based on properties (PublishTrimmed, PublishSingleFile, etc), but if the user sets those properties in the project files, they're not checked in the UI.

**Comment by vijayrkn** [comment]
The UI actually sits on top of the publish profile. So it does not inspect the msbuild evaluation for the project.  Having said that, we don't override any properties unless the user explicitly checks/unchecks the checkbox. 

i.e: If trimming is enabled at the project level, publish will honor it. If some explicitly goes and checks & then unchecks it from profile, we will disable the feature at the profile level.

**Comment by vijayrkn** [comment]
![image](https://user-images.githubusercontent.com/3981619/123310229-b5069a80-d4da-11eb-82d0-ab9eee689b14.png)

Here is the final UI with the above changes.

**Comment by agocke** [comment]
This work is done, and the checkboxes will soon be "pre-checked" if the setting is set in the project pages itself. Closing this one out. Great work!
