### ISSUE TITLE
Allow ability to optimize away finally clauses used for foreach

### ISSUE THREAD

**Issue by vargaz** [mono/linker#2031]
This c# code:
```
        var l = new List<int> ();
        foreach (var i in l) {
             ...
        }
```
is compiled to:
```
    IL_0000:  newobj     instance void [System.Collections]System.Collections.Generic.List`1<int32>::.ctor()
    IL_0005:  stloc.0
    IL_0006:  ldloc.0
    IL_0007:  callvirt   instance [System.Collections]System.Collections.Generic.List`1/Enumerator<!0> [System.Collections]System.Collections.Generic.List`1<int32>::GetEnumerator()
    IL_000c:  stloc.1
    .try
    {
      IL_000d:  br.s       IL_0017

      IL_000f:  ldloca.s   V_1
      IL_0011:  call       instance !0 [System.Collections]System.Collections.Generic.List`1/Enumerator<int32>::get_Current()
      IL_0016:  stloc.2
      IL_0017:  ldloca.s   V_1
      IL_0019:  call       instance bool [System.Collections]System.Collections.Generic.List`1/Enumerator<int32>::MoveNext()
      IL_001e:  brtrue.s   IL_000f

      IL_0020:  leave.s    IL_0030

    }  // end .try
    finally
    {
      IL_0022:  ldloca.s   V_1
      IL_0024:  constrained. [System.Collections]System.Collections.Generic.List`1/Enumerator<int32>
      IL_002a:  callvirt   instance void [System.Runtime]System.IDisposable::Dispose()
      IL_002f:  endfinally
    }  // end handler
```

On some platforms, particularly wasm, the try-finally clause causes much worse code to be generated. It would be useful if the linker could get rid of it. This is possible because List<T>.Enumerator.Dispose is an empty method. So the linker could:
- Resolve the virtual call at 0x2a to List<T>.Enumerator.Dispose ()
- Remove the call since its to an empty method on a valuetype
- Remove the now unused ldloca.s
- The finally clause now only contains an endfinally, so the whole clause can be removed

**Comment by MichalStrehovsky** [comment]
Native code generators operate on IR that is better equipped to do this kind of optimizations. For example, RyuJIT has a phase to do this optimization after devirtualization and inlining: https://github.com/dotnet/runtime/blob/a2e36a7693967d04ca0548e2b825d7ec363bd1f3/src/coreclr/jit/fgehopt.cpp#L13-L31.

ILLinker doesn't have an IR. Without that, we would have to hack up something _very carefully_ so that it e.g. doesn't kick in for situations like:

```csharp
using System;

using (var b = new Blah())
{
    Console.WriteLine("Hi");
}

struct Blah : IDisposable
{
    static Blah() => Console.WriteLine("Hello");
    void IDisposable.Dispose() { }
}
```

Doesn't the LLVM backend for WASM have a place where it could do the same pass that RyuJIT does?

**Comment by vargaz** [comment]
It might be possible to do this in the mono AOT compiler as well.

**Comment by vargaz** [comment]
Implemented this in mono instead, it would still be nice to have support in the linker through since it has a more global view of the program, i.e. it can also optimize the case of iterating over an IEnumerable if it can prove that all possible Dispose () methods are empty.
