### ISSUE TITLE
CallSite.ReturnType.MetadataType sometimes gives incorrect results

### ISSUE THREAD

**Issue by LakshanF** [mono/linker#2090]
`MethodBodyScanner `has a check for IL Opcode calli for [void](https://github.com/mono/linker/blob/caeaf2a3fb3f636805fdd4881df4f9a539fff8f6/src/linker/Linker.Dataflow/MethodBodyScanner.cs#L535) and` ReturnType.MetadataType` gives incorrect results. Specifically, for a call on `System.DateTime::UpdateLeapSecondCacheAndReturnUtcNow()` returns `OptionalModifier`. `signature.ReturnType.GetElementType ().MetadataType` return the correct `MetadataType.Void`

Relevant Code is below
[C#](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.Private.CoreLib/src/System/DateTime.Windows.cs#L189):    `s_pfnGetSystemTimeAsFileTime(&fileTimeNow);`

IL: `calli      unmanaged cdecl void modopt(System.Runtime.CompilerServices.CallConvSuppressGCTransition)(uint64*)`

EXPECT: `MetadataType.Void`

**Comment by MichalStrehovsky** [comment]
Oh, Cecil.

We probably have this problem wherever `.MetadataType` is used on something that we didn't call `Resolve` on because there can be a modifier. C# started putting them on a lot of things lately.

**Comment by LakshanF** [comment]
This behavior seems to be by design
