### ISSUE TITLE
NullReferenceException at Mono.Linker.Steps.MarkStep.SearchPropertiesForMatchingFieldDefinition.

### ISSUE THREAD

**Issue by fernandovm** [mono/linker#213]
Dear, after update Visual Studio 2017 to 15.5.2 when I try generate a new Android release of my app I get this error:

error MSB4018: The "LinkAssemblies" task failed unexpectedly.
error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
error MSB4018: at Mono.Linker.Steps.MarkStep.SearchPropertiesForMatchingFieldDefinition(FieldDefinition field)
error MSB4018: at Mono.Linker.Steps.MarkStep.MarkFields(TypeDefinition type, Boolean includeStatic, Boolean markBackingFieldsOnlyIfPropertyMarked)
error MSB4018: at Mono.Linker.Steps.MarkStep.ApplyPreserveInfo(TypeDefinition type)
error MSB4018: at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
error MSB4018: at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
error MSB4018: at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
error MSB4018: at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
error MSB4018: at Mono.Linker.Steps.MarkStep.Initialize()
error MSB4018: at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
error MSB4018: at Mono.Linker.Pipeline.Process(LinkContext context)
error MSB4018: at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
error MSB4018: at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
error MSB4018: at Xamarin.Android.Tasks.LinkAssemblies.Execute()
error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.d__26.MoveNext()

I already reported the issue on VS community (https://developercommunity.visualstudio.com/content/problem/175090/the-linkassemblies-task-failed-unexpectedly-with-v.html), but, anybody know some productive way of I investigate/debug this issue? How can I collect more clues about the problem? Although configured VS in diagnostic mode, I do not see any useful information in the logs that might indicate the motivation for the problem.

Are there some way of detect what the specific motivation of the exception?

**Comment by fernandovm** [comment]
Great news, thank you so much @marek-safar.

**Comment by fernandovm** [comment]
@marek-safar, I did see fastly the code of SearchPropertiesForMatchingFieldDefinition method when I open this issue and though I had see that maybe are missing some checks, I could not imagine a specific situation that would expose the problem. By curiosity, could you give me a simple class definition hable to generate this issue? This could be usefull as base of some workaround.

**Comment by marek-safar** [comment]
Please see referenced pull request, it has code fix as well as test which shows how to hit the path

**Comment by fernandovm** [comment]
Sure, very good, again, thank you so much!
