### ISSUE TITLE
Broken type references when using copyused mode

### ISSUE THREAD

**Issue by vitek-karas** [mono/linker#2138]
Repro is pretty simple:

New console app:
```C#
using System;
using System.Runtime.InteropServices;

namespace ReproCopyUsedBug
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(RuntimeInformation.FrameworkDescription);
            Console.WriteLine(RuntimeEnvironment.GetRuntimeDirectory());
        }
    }
}
```

Publish with:
```console
dotnet publish -r win-x64 -p:PublishTrimmed=true -p:TrimMode=copyused
```

Try to run:
```console
Unhandled exception.
   Cannot print exception string because Exception.ToString() failed.
```

The problem is in `System.Runtime.InteropServices.RuntimeInformation.dll`, the `RuntimeInformation.get_FrameworkDescription` calls `CustomAttributeExtensions.GetCustomAttribute<T>(...)`. The type ref on that dll is pointing to `System.Runtime.dll`, which has a type forwarder for it which points to `CoreLib`.

When trimmed in copyused mode, we rewrite the typereference to point directly to `CoreLib` and remove the typeforwarder from `System.Runtime.dll`, but then when deciding how to output the `System.Runtime.InteropServices.RuntimeInformation` we mark it as "copy" and effectively throw away any changes (including the rewrite of the type ref).

Note that this works if you omit the call to `RuntimeEnvironment` since now we will remove `System.Runtime.InteropServices.dll` completely, which will force us to rewrite `System.Runtime.InteropServices.RuntimeInformation` as that has an assembly ref to it.

**Comment by vitek-karas** [comment]
@sbomer, can you please take a look? This is currently blocking @odhanson as this is a regression from .NET 6 Preview 3 (where it worked).

**Comment by vitek-karas** [comment]
Also - any idea about a potential workaround... ?

**Comment by odhanson** [comment]
Thanks @vitek-karas

**Comment by sbomer** [comment]
I don't have any ideas for a workaround unfortunately.

Thanks for the repro. The copyused behavior has always seemed inconsistent to me - sometimes we would copy, sometimes we would rewrite their typerefs, and the decision was based on whether the assembly referenced any removed assembly. But it's possible that the assembly doesn't reference any removed assembly, yet still references a removed forwarder in a kept assembly.

I can see two possible fixes:
1. Always save copyused assemblies
2. Save copyused assemblies based on whether scope update rewrote any scopes (_not_ on whether it removed any assemblyrefs)

The first would be simpler, but might be a bigger behavior change (people might expect the behavior where copyused sometimes results in R2R info being kept). So I think we should track whether the scope update changed anything.

**Comment by sbomer** [comment]
Actually - would keeping `TrimMode=link` be an acceptable workaround?

**Comment by odhanson** [comment]
> Actually - would keeping `TrimMode=link` be an acceptable workaround?

Link is a big can of works for us. We would love to use it at some point, but it's a big effort, and right now our focus is on Apple Silicon and universal binaries support.
