### ISSUE TITLE
Implications of RUC on nested types

### ISSUE THREAD

**Issue by MichalStrehovsky** [mono/linker#2151]
We currently consider types nested under RUC types as RUC themselves.

This means:

```csharp
[RUC]
class Foo
{
    // [RUC] is implied
    class Nested { }

    // Treat as RUC as well?
    struct Bar { }

    // Treat as RUC as well?
    interface Baz { }

    // Treat as RUC as well?
    deleate Woo();

    // Also RUC?
    enum MyEnum { One, Two }
}
```

I see two options:

1. Treat RUC the same as 99% other attributes that don't get inherited from their owning type.
2. Have non-class nested types "break" the RUC inheritance chain (types nested under them no longer have RUC either, including if there's any classes) and document the weirdness.

I prefer the first option because it's simpler and I like simple, but I also don't know what lead us to deciding we want it to be inherited in the first place (the inheritance wouldn't be my first choice).

Cc @tlakollo @vitek-karas @agocke

**Comment by vitek-karas** [comment]
That's a good point. I also prefer first option - it will mean adding more attributes in some places, but it shouldn't be too bad.
The only downside of this approach is that it will not work for compiler generated closures (lambdas, local functions), but that's the existing problem of support for compiler generated code in general (the current solution would mostly work in those cases).

**Comment by agocke** [comment]
I think there's an option 3:

RUC applies if any type in the FQN has RUC on it, and RUC would be a valid annotation on that type.

**Comment by agocke** [comment]
I would be fine with option 1 though

**Comment by tlakollo** [comment]
The expectation is that it would be like with derived classes that we print the new IL2109 to say "hey you might want to put RUC here too since the base class has RUC"? Or we would simply imply that nested classes are safe to use unless they are also marked with RUC?

**Comment by MichalStrehovsky** [comment]
> "hey you might want to put RUC here too since the base class has RUC"

RUC on value types and interfaces is hard to enforce because both can be "created" without running a constructor. We don't want that.

Option 1 basically says that RUC only applies to the non-type members of the type it's applied to and nested types are unaffected. As Vitek pointed out, we need to make sure this works fine with the code that handles compiler generated closure classes (maybe this will already work).

**Comment by vitek-karas** [comment]
> we need to make sure this works fine with the code that handles compiler generated closure classes

I don't see this as a must have. Lambdas and local functions are already broken in lot of cases because we can't detect this automatically (unlike state machines). But they have an easy workaround - put the attribute on them. I would be fine if RUC on the type didn't apply to lambdas in 6.0. Obviously not great UX, but it's easy to workaround and pretty easy to explain.

And also - RUC on type will not be very common I hope - we want it because we want to annotate all our libraries, even those which are just not trim compatible. I expect that 3rd parties will not bother annotating libraries which can't be made trim compatible and will be fine with the warning-per-library they get automatically today.

**Comment by agocke** [comment]
I see both sides. On one hand, I think we should eventually try to have RUC apply to nested functions. F# already inlines nested functions if it can prove they don't escape and I could see it being the same for C# eventually. If we don't have transitive application then it can be unpredictable whether or not the linker will provide a warning.

However, the complexity around structs and interfaces convinces me that we should have a different behavior for nested types. RUC doesn't just suppress warnings, it also implies a contract. If RUC applies to the nested interface, then it would have to apply through implementations, which is quite subtle.

Let's go with option 1.
