### ISSUE TITLE
Error building with 6.0.100-preview.6.21376.2

### ISSUE THREAD

**Issue by jonathanpeppers** [mono/linker#2178]
Context: https://github.com/xamarin/xamarin-android/pull/6131

Our build is hitting an error such as:
```
CSC : error CS1705: Assembly 'illink' with identity 'illink, Version=6.0.100.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'Mono.Cecil, Version=0.11.4.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e' which has a higher version than referenced assembly 'Mono.Cecil' with identity 'Mono.Cecil, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'
```

I was able to reproduce this with `dotnet new classlib` and adding a class that uses:

```xml
<PackageReference Include="Microsoft.NET.ILLink" Version="6.0.100-preview.6.21376.2" />
```

`.binlog` included: [foo.zip](https://github.com/mono/linker/files/6893332/foo.zip)

**Comment by mateoatr** [comment]
Dup of #2173. Should be fixed by https://github.com/mono/linker/pull/2174.
