### ISSUE TITLE
How to whitelist third-party resources?

### ISSUE THREAD

**Issue by JustArchi** [mono/linker#218]
I'm using **[Humanizer](https://github.com/Humanizr/Humanizer)** library in my app in order to provide nice localization of `TimeSpans`. I noticed that mono-linker (`ILLink.Tasks 0.1.4-preview-1222833`) automatically removes Humanizer resources (those under e.g. `pl/Humanizer.resources.dll`) as apparently they're not detected as being used. The core library itself (`Humanizer.dll`) is being linked properly, but even its root resources (`Humanizer.resources.dll`) are not.

I tried to root entire `<assembly fullname="Humanizer" />` in order to "force" inclusion of the resources, but without much luck as despite of entire library being properly linked, its resources are still being removed. I also tried to root `<assembly fullname="Humanizer.resources" />`, but since there is no such assembly (as those are resource files only), mono-linker can't locate them.

Is there any way to keep third-party resources (localization) files while still using mono-linker? Perhaps there is some switch I'm not aware of. If not, it'd probably be a good idea to add support for this.

Thank you in advance for response.

**Comment by JustArchi** [comment]
BTW the "regression" happened between `0.1.4-preview-981901` and `0.1.4-preview-1184387`, since in 981 version resources are still included properly.

**Comment by erozenfeld** [comment]
@sbomer @JosephTremoulet Looks like a native trimming issue.

**Comment by erozenfeld** [comment]
@marek-safar Please reassign this issue to @JosephTremoulet. Apparently I don't have permissions to do that.

**Comment by sbomer** [comment]
@erozenfeld, I think I see the issue. I must have changed how the managed assemblies to consider for trimming are computed, and the native trimming candidates are computed from the managed set, resulting in them including resource assemblies.

@JustArchi, as a workaround until this is fixed, try placing the following in your project:

```
<Target Name="AddBackResourceAssemblies"
        AfterTargets="_FindNativeDeps">
  <ItemGroup>
    <_NativeResolvedDepsToPublish Remove="@(_NativeResolvedDepsToPublish->WithMetadataValue('AssetType', 'resources'))" />
  </ItemGroup>
</Target>
```

**Comment by JustArchi** [comment]
Thank you a lot for fixing the issue. I'm happy to confirm that ILLink.Tasks in version `0.1.4-preview-1317495` works properly for my case ❤️
