### ISSUE TITLE
Reflection access from Pinvokes and InternalCalls should warn at callsite

### ISSUE THREAD

**Issue by sbomer** [mono/linker#2188]
Currently when the linker sees a PInvoke or InternalCall that is an instance method it preserves all fields of the declaring type: https://github.com/mono/linker/blob/762278c9c3e60f5a82733dc0386bd0cf7f0a2d22/src/linker/Linker.Steps/MarkStep.cs#L3266

This produces warnings if any of the fields is annotated. Would it make more sense to warn at the callsites to the interop method? Currently the origin is the interop method itself, which is unusual in cases where the required fields depend on the callsite - see https://github.com/dotnet/runtime/pull/56593#discussion_r681868368.

@MichalStrehovsky @LakshanF

**Comment by MichalStrehovsky** [comment]
This is not a user scenario - it's some quirk for Mono.

P/invoke cannot be an instance method on CoreCLR and InternalCall is only used on COM classes that cannot have fields anyway. You'll get a `TypeLoadException` on this with CoreCLR.

I don't think we need to bother with this scenario.

**Comment by sbomer** [comment]
Thanks! Closing.
