### ISSUE TITLE
We should automatically retain any method with a ModuleInitializer attribute and its dependencies

### ISSUE THREAD

**Issue by kg** [mono/linker#2314]
Any method with the [ModuleInitializer](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.moduleinitializerattribute?view=net-5.0) attribute is run at module load time for its assembly. The linker should automatically retain these methods and any of their dependencies unless the assembly as a whole is linked out, IMO. This is necessary for Source Generators to be usable without a bunch of custom Linker configuration.

**Comment by MichalStrehovsky** [comment]
Illink keeps the module initializer method (which is the thing the C# compiler generates to call all methods marked `ModuleInitializer`).

In fact, illink keeps all methods on the module type, not just the module initializer method:

https://github.com/dotnet/linker/blob/8097e395086a58853c94f557840afd094b071905/src/linker/Linker.Steps/MarkStep.cs#L1426-L1432

What's the scenario where this is not sufficient? A method marked `ModuleInitializer` that is not actually called from the actual module initializer wouldn't run at module load time anyway.

**Comment by kg** [comment]
OK, just wanted to make sure it would work - I grepped the source code for the attribute and didn't see anything, was about to rely on it.

According to the docs I read, any method with ModuleInitializer on it will be a module initializer, and the compiler combines them. Is that not true?
