### ISSUE TITLE
mono-linker is no longer able to optimize targets for non-native runtimes

### ISSUE THREAD

**Issue by JustArchi** [mono/linker#242]
```
C:\Program Files\dotnet\sdk\2.1.4\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.CrossGen.targets(72,5): error : Unable to find resolved path for 'C:\Users\appveyor\.nuget\packages\runtime.linux-arm.microsoft.netcore.app\2.0.0\runtimes\linux-arm\native\..\..\..\tools\crossgen.exe'. [C:\projects\archisteamfarm\ArchiSteamFarm\ArchiSteamFarm.csproj]
```

The last working version is `0.1.4-preview-1222833`, `ILLink.Tasks` in version `preview-13*` fails for non-native runtime identifiers.

It should be possible to reproduce easily with `dotnet publish -r linux-x64` (on Windows). Thank you in advance for looking into this.

**[CI output for reference, if needed](https://ci.appveyor.com/project/JustArchi/archisteamfarm/build/4926-master#L457)**

**Comment by erozenfeld** [comment]
@sbomer Looks like this is caused by https://github.com/mono/linker/pull/192 . Can you take a look?

**Comment by sbomer** [comment]
@JustArchi, https://github.com/mono/linker/pull/192 introduced native precompilation, but unfortunately we don't support this when cross-targeting. To run the linker while cross-targeting without native precompilation, set `<CrossGenDuringPublish>false</CrossGenDuringPublish>`.

@erozenfeld We should probably turn off native precompilation by default for cross-targeting scenarios, or at least provide a better error message. I'll look into it.

**Comment by JustArchi** [comment]
If mono-linker could detect if host machine matches target runtime and automatically disable crossgen if it doesn't then that would probably be the best solution, but if it's not possible then turning it off by default is probably a good thing, at least until it's better supported.

In any case thanks a lot for looking into it, I appreciate all of your work ❤️
