### ISSUE TITLE
DAM interaction with RequiresAttribute

### ISSUE THREAD

**Issue by tlakollo** [mono/linker#2739]
There is already a defined behavior for the interaction between RequiresUnreferencedCode and DynamicallyAccessedMembers. For example, there is the following [doc](https://github.com/dotnet/linker/blob/main/docs/design/DAM-on-type-and-RUC-interaction.md) that explains the interaction between DAM and RUC on a type. 
This PR is to discuss what should be the behavior in the case we access members annotated with RequiresAssemblyFiles or RequiresDynamicCode via reflection/DAM. 
Currently:
- Both attributes don't warn when accessed via reflection nor the marking made via DynamicallyAccessedMembers.
- Code in runtime for NativeAOT will only warn on reflection access if the member is annotated with RequiresUnreferencedCode

The question becomes what should happen with the following:
```C#
[RequiresAssemblyFiles ("RAF")]
[RequiresDynamicCode ("RDC")]
class DangerousClass
{
	public static void DangerousMethod () { }
}

static void TestDAMAccess ()
{
	typeof (DangerousClass).RequiresPublicMethods ();
}

public static void RequiresPublicMethods ([DynamicallyAccessedMembers (DynamicallyAccessedMemberTypes.PublicMethods)] this Type type) { }
```
Currently, we will mark the members and threat DAM as reflection access but not generate any warnings about it. Eventually, if the method ends up being called we will get runtime errors without any previous warning.

**Comment by tlakollo** [comment]
cc @sbomer @jkotas @vitek-karas @agocke @LakshanF

**Comment by sbomer** [comment]
Generally speaking, I think the `RequiresFeature` attributes are independent of reflection and `DynamicallyAccessedMembers` annotations (except `RequiresUnreferencedCode` which was specifically designed for trim analysis).

You can easily use reflection to invoke methods attributed with `RequiresFeature` to get around static checks, and the code will throw at runtime if the feature is disabled, trimming or no trimming. I think trim analysis shouldn't be in the business of trying to detect such patterns in general. Instead we should aim to produce warnings when trimming would introduce differences in the runtime behavior.

Are `RequiresDynamicCode`/`RequiresAssemblyFiles` different? I can't think of a way to introduce a difference in behavior in a trimmed app by reflecting over `RequiresDynamicCode` APIs, except for example by introducing dependencies on the presence of specific IL members that would be removed when trimming - and we haven't been emitting warnings for that kind of thing so far. Dynamic codegen that tries to do "reflection unsafe" things like call reflection APIs are supposed to be producing warnings in the codegen code that uses reflection to obtain references to the reflection APIs, I think.

**Comment by MichalStrehovsky** [comment]
I think a good way to think about it is whether we would want:

```csharp
Activator.CreateInstance(Type.GetType(someUnknownString));
```

to generate a single file warning (since the type/ctor might have been marked `RequiresAssemblyFiles` for all we know).

I'm leaning towards saying no to that - it would be too much noise.

We have similar attributes to mark e.g. APIs that are only available on Windows, and there's a matching analyzer for it that is always active - if we were to analyze reflection use of these, would we also detect the platform specific APIs used through reflection?

We do this for the trimming-related attributes because we require full knowledge of reflection within the app. The warnings come for "free". But other form factors don't require reflection usage that can be statically reasoned about.

**Comment by sbomer** [comment]
The behavior we discussed was implemented in https://github.com/dotnet/runtime/pull/83085. https://github.com/dotnet/runtime/pull/104760 is removing references to this issue, then we can close it out.
