### ISSUE TITLE
PublishTrimmed should use a linker that matches the TargetFramework

### ISSUE THREAD

**Issue by sbomer** [mono/linker#3029]
We need a long-term solution for back-compat issues when using a newer SDK to trim apps targeting older TFMs. Some issues encountered so far:
- https://github.com/dotnet/linker/issues/2998
- https://github.com/dotnet/runtime/pull/72143#issuecomment-1233715839

We will hit a similar situation with planned breaking changes in 8.0, where it would be difficult to maintain a back-compat path. Maybe there are more examples, but this one comes to mind:
- https://github.com/dotnet/runtime/issues/117157

The solution will most likely (pending the outcome of broader discussion) be to use the 6.0 linker when targeting .net6, etc. This issue tracks the technical side of that proposed solution.

**Comment by vitek-karas** [comment]
I think it makes sense to keep 7.0 as-is, unless we get lot of feedback otherwise.

**Comment by jtschuster** [comment]
Leaving a note for once this is finalized to check on the linker benchmark in dotnet/performance and make sure that the benchmark will still use the latest version of the linker.
