### ISSUE TITLE
ILLink.Task fails when used in latest SDK

### ISSUE THREAD

**Issue by ericstj** [mono/linker#308]
/cc @sbomer 
Using the latest dotnet SDK, add the following
```
    <PackageReference Include="ILLink.Tasks" Version="0.1.5-preview-1461378" />
```
Publish the project.

It will fail with
```
2>The "GetRuntimeLibraries" task failed unexpectedly.
2>System.InvalidCastException: [A]NuGet.ProjectModel.LockFile cannot be cast to [B]NuGet.ProjectModel.LockFile. Type A originates from 'NuGet.ProjectModel, Version=4.7.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35' in the context 'LoadFrom' at location 'C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\Sdks\Microsoft.NET.Sdk\tools\net46\NuGet.ProjectModel.dll'. Type B originates from 'NuGet.ProjectModel, Version=4.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' in the context 'LoadFrom' at location 'C:\Users\ericstj\.nuget\packages\illink.tasks\0.1.5-preview-1461378\tools\net46\NuGet.ProjectModel.dll'.
2>   at Microsoft.NET.Build.Tasks.LockFileCache.GetLockFile(String path)
2>   at ILLink.Tasks.GetRuntimeLibraries.Execute()
2>   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

This is  the same bug I fixed/worked-around here: https://github.com/dotnet/standard/pull/722

@nguerrera do you have an idea about a public contract we can have around this to avoid these issues in the future?  Either we get everyone to agree on where to load NuGet from or we version the cache objects (like I did in my PR).  The latter is less good since it means we don't benefit from the cache when we get out of sync.

**Comment by los93sol** [comment]
Just upgraded VS17 this morning and I'm getting the same error.  Is there a manual fix for this?

**Comment by los93sol** [comment]
Is this supposed to be fixed in the current nuget package?

**Comment by ericstj** [comment]
You do need a new package to get the fix.  It looks to me like this hasn't been produced in a while.  @sbomer can you please do what's necessary to build and produce a new package?  Without folks are broken using ILLink and the latest public SDK.

**Comment by los93sol** [comment]
Just FYI, it doesn’t look like a new version has been published yet

**Comment by sbomer** [comment]
@los93sol, thanks for your patience. Could you give https://dotnet.myget.org/feed/dotnet-core/package/nuget/ILLink.Tasks/0.1.5-preview-1841731 a try? This version has @ericstj's fix (https://github.com/mono/linker/pull/309).
