### ISSUE TITLE
IL Linker does not remove unused classes / methods

### ISSUE THREAD

**Issue by a-student** [mono/linker#320]
It is stated [here](https://github.com/dotnet/core/blob/master/samples/linker-instructions.md) that
> The linker removes code in your application and dependent libraries that are not reached by any code paths

I am following [these instructions](https://github.com/dotnet/core/blob/master/samples/linker-instructions.md#instructions). Before publishing the app I add unused class to the project:
```
echo internal class UnusedClass { private class UnusedNestedClass { private void UnusedMethod() { System.Console.WriteLine("This method is never called.");}}}> UnusedClass.cs
```
To make sure the linker processes the main assembly add these lines to the `testapp.csproj` file:
```xml
<PropertyGroup>
    <ExtraLinkerArgs>-c link -u link -t -l none -b true --skip-unresolved true --verbose</ExtraLinkerArgs>
</PropertyGroup>
```
My publish command:
```
dotnet publish -c release -r win-x64 -o out /p:ShowLinkerSizeComparison=true
```
After publishing decompile `out/testapp.dll` (I use ILSpy).

_Expected_: UnusedClass is removed.
_Actual_: UnusedClass is still there.

**dotnet --version**: 2.1.300-preview2-008533
**IL Linker** from [this package](https://dotnet.myget.org/feed/dotnet-core/package/nuget/ILLink.Tasks/0.1.5-preview-1461378)

**Comment by erozenfeld** [comment]
@a-student By default all methods in all application assemblies are rooted. If you want only Main method to be the root, you need to set RootAllApplicationAssemblies to false.

Please try publishing with this command:

dotnet publish -c release -r win-x64 -o out /p:ShowLinkerSizeComparison=true /p:RootAllApplicationAssemblies=false

This document 
https://github.com/mono/linker/blob/fbe310a0c018ddcd701fe9ff91aa61ec6c026221/corebuild/README.md
has more up-to-date instructions than
https://github.com/dotnet/core/blob/master/samples/linker-instructions.md#instructions

**Comment by a-student** [comment]
I am using the Blazor project and, unfortunately, it does not allow passing options to the linker via `/p:`. Is there another way to make the Main method to be the only root, that is, by passing command line arguments directly to the linker? Blazor msbuild target has separate property for this (`AdditionalMonoLinkerOptions`).

**Comment by erozenfeld** [comment]
Can you specify
```
<PropertyGroup>
    <ExtraLinkerArgs>-c link -u link -t -l none -b true --skip-unresolved true --verbose</ExtraLinkerArgs>
    <RootAllApplicationAssemblies>false</RootAllApplicationAssemblies>
</PropertyGroup>
```
in your csproj file?
