### ISSUE TITLE
IL1012 - ILTrimmer has encountered an unexpected error

### ISSUE THREAD

**Issue by BillFulton** [mono/linker#3225]
Fyi error appeared when building an unmodified out-of-the box MAUI iOS app with iPhone 14 Plus iOS 16.4 simulator.

Versions attached.

<img width="661" alt="Versions" src="https://github.com/dotnet/linker/assets/11141569/7914c55a-a5b4-4090-bb0d-c5c3feed625e">

**Comment by sbomer** [comment]
@BillFulton thanks for reporting the issue! Would you be able to provide an MSBuild binlog for us to diagnose this?

**Comment by awasilik** [comment]
Hey, I encountered same problem in my project. I described it here:
https://github.com/dotnet/runtime/issues/91880

**Comment by BillFulton** [comment]
Sorry @sbomer, I missed seeing your email. I've updated to the latest, and the error has gone away. Cheers Bill
