### ISSUE TITLE
Blazor: error IL1012 IL Trimmer has encountered an unexpected error AND error NETSDK1144: Optimizing assemblies for size failed.

### ISSUE THREAD

**Issue by damien7792** [mono/linker#3229]
Hello,

here's the error(s) I'm getting during deployment of a Blazor app:

ILLink : error IL1012: IL Trimmer has encountered an unexpected error. Please report the issue at https://github.com/dotnet/linker/issues
  Fatal error in IL Linker
  Out of memory.

/usr/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.ILLink.Tasks/build/Microsoft.NET.ILLink.targets(86,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.

I'm not sure which error is the cause of the other one, but I'm prevented from deploying an app I could deploy last week without any problems.

Thanks

**Comment by jtschuster** [comment]
It looks like you're using a version of the SDK that had a memory consumption issue that's now fixed. If you download the newest SDK (https://dotnet.microsoft.com/download) and retry, does it work?

**Comment by damien7792** [comment]
Thanks @jtschuster , that worked!
