### ISSUE TITLE
Preserve more context for EventDataAttribute

### ISSUE THREAD

**Issue by erozenfeld** [mono/linker#333]
Two common patterns for trace logging payload is using classes marked by [EventData] or using anonymous types: https://docs.microsoft.com/en-us/windows/desktop/tracelogging/tracelogging-managed-quick-start . EventSource uses reflection to get to the properties of the payload.
The linker already preserves public instance methods of reachable types with [EventData] attribute: https://github.com/mono/linker/blob/master/linker/Linker.Steps/MarkStep.cs#L1012 
It should do the same for reachable anonymous types.

@sbomer @jeffschwMSFT @brianrob

**Comment by morganbr** [comment]
.NET Native keeps property accessors on anonymous types, but not the rest of the instance methods and it seems to work pretty well.

**Comment by marek-safar** [comment]
The logic should be conditional, e.g. only when an anonymous type is used with EventSource::Write<T>

**Comment by brianrob** [comment]
Conditional on EventSource::Write<T> should cover most cases, but if it's possible to do this for EventSource all up, that might be preferrable, as there are internal cases like EventSource::WriteEventString that don't go through Write<T>, but attempting to list them in linker source code would mean that EventSource internals have leaked into the linker, and I'd rather not do this.

**Comment by marek-safar** [comment]
This is and will be handled with linker flow attributes going forward
