### ISSUE TITLE
Linker doesn't remove overridden methods in unused classes

### ISSUE THREAD

**Issue by vargaz** [mono/linker#367]
The linker doesn't remove overridden methods even if no instances of the containing type are created,
which means the ctors are removed, so there is no way to create instances of the type.

This affects code in mscorlib, i.e. the override ModuleBuilder::GetTypes () is retained even if SRE is not used, causing a large part of SRE to also be retained, since GetTypes () ends up calling TypeBuilder::CreateType ().

Testcase:
```
using System;

public class ParentClass
{
	public virtual void foo () {
	}
}

public class ChildClass : ParentClass
{
        // This ends up being retained
	public override void foo () {
	}

	public void bar () {
	}
}

public class Tests
{
	public static void Main () {
		var p = new ParentClass ();
		var t = typeof (ChildClass);
		Activator.CreateInstance (t);
		p.foo ();
	}
}
```

**Comment by mrvoorhe** [comment]
We have logic to handle some reflection scenarios.  We don't currently handle `Activator.CreateInstance`, but if we did then  `ChildClass.ctor()`  would be retained.

Did you intentionally not store the result of `Activator.CreateInstance (t);`?  there might be a niche opportunity to not mark overridden virtual methods until an instance is stored or another member of the class is used.  Would need to think about it more.

**Comment by vargaz** [comment]
That line is just there to show that its not possible to create instances of ChildClass at runtime, so ChildClass::foo can be removed.

**Comment by mrvoorhe** [comment]
I want to write a few more tests to make sure I'm not missing something, but here is what I have so far

https://github.com/mono/linker/compare/master...Unity-Technologies:master-derived-types-no-ctor

**Comment by vargaz** [comment]
What is the status of this ?

**Comment by mrvoorhe** [comment]
I have a branch almost ready that will cover this scenario and many others.   The branch builds on the interface sweeping PR https://github.com/mono/linker/pull/394 so that needs to land first.

**Comment by mrvoorhe** [comment]
Status update.

It's going to be a bit longer.  This isn't a high priority for us so I've been working on it on the side, which has made progress slow.  And  "Base type sweeping", which would address your case, has turned out to be far more complicated than I initially realized due to needing to respect visibility rules for nested types used from static's.

**Comment by marek-safar** [comment]
This works as expected with master version
