### ISSUE TITLE
Need a safe way to supply a long list of assemblies to link

### ISSUE THREAD

**Issue by SteveSandersonMS** [mono/linker#379]
While investigating #369, I found that the reason the linker was complaining that it couldn't find certain assemblies was because it was looking for malformed paths. Certain characters were missing from apparently random places in the middle of path strings.

The reason for this appears to be:

 1. Blazor's build config generates a command for the linker that includes `-a path1\Assembly1.dll -a path2\Assembly2.dll -a path3\Assembly3.dll ...`, where the list of assemblies is all those transitively reachable from the app's entrypoint assembly
 2. All those assemblies can be in totally different directories because of how NuGet works. Therefore if the linker is to find them, we have to specify their locations explictly with an `-a path\AssemblyName.dll` entry for each one, or alteratively specify `-d path` for each one, which is equally problematic.
 3. The `Microsoft.CodeAnalysis.CSharp.Features` assembly pulls in a *long* list of transitive dependencies, as do various other NuGet packages in real-world use.
 4. The total length of the generated command, then, can easily be many thousands of characters, given that each dependency's path could be 100-200 chars.
 5. MSBuild has a longstanding bug whereby extremely long commands get corrupted, removing characters from arbitrary points in the middle: https://github.com/Microsoft/msbuild/issues/2530
 6. Thus the linker receives corrupted paths and fails

Proposed workaround:

 * Is there any existing way to specify the paths to a large number of transitive dependencies *without* including them all in the command-line command? For example, do any of the linker config file formats allow us to give path hints for transitive dependencies? Blazor already generates a linker config file as part of its build process, so we could extend this to making it list all the dependencies and their paths.
 * Or if not, would you be open to adding a further option to the linker, which is to let the user pass a file that gives the paths to all the dependencies, or perhaps just a list of directory paths in which to search for referenced assemblies?

**Comment by marek-safar** [comment]
List of directory paths is problematic as we'd need conflict resolution logic. What about supporting response file where you could put all the command line arguments.

I think there is even issue about that

**Comment by SteveSandersonMS** [comment]
> What about supporting response file where you could put all the command line arguments.

Sounds ideal to me.

**Comment by erozenfeld** [comment]
You can specify -x, -i, and -a parameters in a file, e.g., -a @foo.rsp.

https://github.com/mono/linker/blob/master/linker/Linker/Driver.cs#L315
https://github.com/mono/linker/blob/master/linker/Linker/Driver.cs#L197
https://github.com/mono/linker/blob/master/linker/Linker/Driver.cs#L206
https://github.com/mono/linker/blob/master/linker/Linker/Driver.cs#L211

**Comment by kakins** [comment]
Forgive me, I'm not as familiar with the details of how mono/Blazor work just yet.  I've just started working with the framework.  I've also experienced this issue trying to add Microsoft.CodeAnalysis.CSharp.Scripting.  Is there a temporary recommended way to get around the error that @SteveSandersonMS described?

**Comment by marek-safar** [comment]
The linker now supports response file input

**Comment by detachmode** [comment]
@marek-safar 
Does this mean that we can use CSharpScripting soon in Blazor?
If yes, is there any way to get a preview of that sooner?

**Comment by xaviersolau** [comment]
> The linker now supports response file input

In what version will it be available? I tried with Blazor preview 6 but it still doesn't work....

**Comment by anoooin** [comment]
Hi @marek-safar ,

Can you kindly confirm when will the fix for this issue be released?

Thank you,
Anusha

**Comment by marek-safar** [comment]
I believe Blazor P7 should have the fix

**Comment by StevenTCramer** [comment]
@marek-safar Given this issue was closed, I opened another #11887 and its marked as 3.1 :(
So I hope you are right.

**Comment by SteveSandersonMS** [comment]
@marek-safar @StevenTCramer Whatever issue exists with this will almost definitely still exist in Blazor preview 7, because we haven't changed any part of client-side Blazor's build mechanism in preview 7. We did move to a newer version of Mono, but that isn't what determines the command that is passed to the linker.
