### ISSUE TITLE
Dependency trees, or: why is System.Drawing.Primitives being deployed in a console app?

### ISSUE THREAD

**Issue by terrajobst** [mono/linker#391]
From https://github.com/dotnet/standard/issues/703:

@voltagex wrote:

> I've got a console app that I've turned on linking and trimming for. A complete standalone version targetting win-x64 is about 40MB, which isn't too bad I guess.
> 
> What I can't work out is _why_ some of the runtime is being included in a simple app, e.g.
> 
> * System.Security.Claims.dll (unused)
> * System.IO.Compression.dll (unused)
> * System.Drawing.Primitives.dll (System.Drawing is removed by linking/trimming but this one isn't)
> 
> I'd like to be able to see _why_ certain assemblies are being pulled in, and if they're not needed, get rid of them completely.

**Comment by erozenfeld** [comment]
Also, by default the linker won't trim application assemblies and its definition of application assemblies may not be what you expect. Try running with RootAllApplicationAssemblies set to false in your csproj file.
