### ISSUE TITLE
Building linker on windows requires Developer Prompt or Visual Studio 2015

### ISSUE THREAD

**Issue by jkoritzinsky** [mono/linker#422]
After cloning this repository, I noticed that it requires VS2015 to build on Windows. Is there any chance we can enable building with VS2017 or VS2019 (likely just requires using vswhere to locate an installation)? I would prefer to not have to go install VS2015 just for this repository.

**Comment by mrvoorhe** [comment]
What errors are you seeing?

I'm able to build with VS2017, although I do have VS2015 installed.
