### ISSUE TITLE
Support for default interface methods

### ISSUE THREAD

**Issue by MichalStrehovsky** [mono/linker#427]
.NET Core 3.0 (and possibly [.NET Standard 2.1](https://github.com/dotnet/standard/pull/1019)) is adding support for non-abstract instance methods on interfaces in support of the C# 8.0 language feature. [Spec here](https://github.com/dotnet/coreclr/pull/21564).

IL Linker will need to understand what this semantic means and:

* Be able to scan instance methods on interfaces
* If IL Linker has any sort of interface method resolution logic, this logic will need to be updated to understand the resolution to default interface methods
* Tests will have to be added

As an aside, C# 8.0 is also adding support for static methods and fields on interface types. The ECMA-335 standard has supported this for a while, but it's likely the scenario is untested in IL Linker (e.g. support for static constructors in interfaces, etc.).

**Comment by marek-safar** [comment]
@baulig could you look into writing tests for default interface methods for us to have coverage for this new scenario.

/cc @steveisok
