### ISSUE TITLE
Emit deterministic output

### ISSUE THREAD

**Issue by vargaz** [mono/linker#433]
Currently, the linker output is not deterministic since the generated assemblies contain a random guid.
Emitting a computed guid like csc does with /deterministic would help build systems avoid rebuilding things which depend on the linker outputs.
This will require changes in both cecil and the linker.

**Comment by vargaz** [comment]
Support in cecil:
https://github.com/vargaz/cecil/tree/deterministic-guid
This is not finished (no tests etc).

**Comment by marek-safar** [comment]
@vargaz please upstream the change we try to keep mono fork without changes

**Comment by mrvoorhe** [comment]
I thought the `-g` option had to be used to make the linker output deterministic?  We made use of it a month or so ago and it seemed to make the output deterministic when used in conjunction with /deterministic passed to csc.

**Comment by mrvoorhe** [comment]
Something is implemented in `Driver.cs` for it

```
case 'g':
						if (!bool.Parse (GetParam ()))
							p.RemoveStep (typeof (RegenerateGuidStep));
						break;
```

**Comment by vargaz** [comment]
Seems to have missed it. The problem with that is that it keeps the guid, so two different assemblies will have the same guid.

**Comment by ViktorHofer** [comment]
@marek-safar as deterministic support is now added to cecil with https://github.com/jbevain/cecil/pull/578 what needs to be done to integrate that into the linker and flow it into corefx?

**Comment by vargaz** [comment]
The cecil submodule needs to be bumped in the linker, but its not trivial:
https://github.com/mono/linker/issues/544

**Comment by vargaz** [comment]
After that, this branch can be merged:
https://github.com/vargaz/linker/tree/deterministic-guid
It will keep the guids, and also avoid overwriting unchanged assemblies, so build systems can avoid further processing of the outputs.

**Comment by vargaz** [comment]
https://github.com/mono/linker/pull/583
