### ISSUE TITLE
Linker incorrectly removes event implementation

### ISSUE THREAD

**Issue by vargaz** [mono/linker#465]
Testcase:
```
public delegate void VectorChangedEventHandler<T>();

public interface IObservableVector<T>
{
	event VectorChangedEventHandler<T> Foo;

	void bar ();
}

class BaseFoo {
	public event VectorChangedEventHandler<object> Foo;

	public BaseFoo () {
	}
}

class ClassFoo : BaseFoo, IObservableVector<object>
{
	public void bar () {
	}
}

class BaseFoo2 : IObservableVector<object>
{
	public event VectorChangedEventHandler<object> Foo;

	public BaseFoo2 () {
		Foo ();
	}

	public void bar () {
	}
}

public class Tests
{
	public static void Main (String[] args) {
		IObservableVector<object> f2 = new BaseFoo2 ();
		f2.Foo += delegate () {};
		IObservableVector<object> f = new ClassFoo ();
		f.bar ();
	}
}
```

Link with:
```
monolinker -a bug.exe -c link
```

In the resulting IL, the ClassFoo class implements IObservableVector<object>, but neither it or its base type contains the implementations for the add_Foo/remove_Foo methods from IObservableVector<object>.

**Comment by vargaz** [comment]
With linker version 973587a221a10d4a73c1ea858b455880aa57e618.

**Comment by mrvoorhe** [comment]
I struggled to reproduce at first.  Then I realized the original test in the github notification email didn't have generics while the latest version of your test case on the site did 😄 

https://github.com/Unity-Technologies/linker/commit/c178fa021c047e2442994e93d8741f6a69695030

I'll look into a fix soon.

**Comment by mrvoorhe** [comment]
This is related to base classes supplying interface members on a derived type AND when generics are involved.  I did not finish looking into it, but it seems like a bug that has always existed and does not appear to be related to the interface sweeping changes that have landed recently.

I'm going to be out for a few weeks on paternity leave so I won't have time to finish fixing this for awhile.  In case it becomes important to fix, here are change sets that may be of help to someone.

Lots of tests to reproduce the issue.  I have some more complex cases than what was reported in this issue, but I think there are probably still some more complex edge cases that would be worth adding tests for to see if they are working correctly or not.
https://github.com/Unity-Technologies/linker/commit/747664550e4288a4e0f88018ce74cf052612cce3

Two aspects to a fix that I have identified so far are

Getting the TypeMapStep to recognize that a member of the base class w/ generics supplies an interface member and to then record that in the AnnotationStore.  I have a very much WIP (and maybe wrong) way of doing that here.  https://github.com/Unity-Technologies/linker/commit/62e740713db8d250b8aabb670a515eef1362dc09 although it does seem to work for a number of cases I wrote.

The second is making the MarkStep aware of which InterfaceImplementation an override is associated with.  This is simpler than the above.  WIP change set here https://github.com/Unity-Technologies/linker/commit/3bbf701a503d5f54acc9ac3fe6b961acb6cdbd0e

If you want all of the changes, here is the branch https://github.com/Unity-Technologies/linker/commits/master-event-and-interface-repro-attempt

There are still some more aspects to this that I have yet to get to.  With the above changes, there are still 3 tests failing.  1 Event and 1 property test.  This may be as simple as not processing events and properties somewhere.  And then 1 is a more complicated test is probably related to how the MarkStep is marking base or overrides.  Maybe base methods need a change similar to what I did with overrides https://github.com/Unity-Technologies/linker/commit/3bbf701a503d5f54acc9ac3fe6b961acb6cdbd0e.  Just a guess.
