### ISSUE TITLE
How to get single file when using ILLink.Tasks ?

### ISSUE THREAD

**Issue by beppe9000** [mono/linker#473]

**Comment by sbomer** [comment]
ILlink.Tasks doesn't support publishing as a single file. You might be interested in some of the alternatives listed in https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md.

**Comment by sbomer** [comment]
@marek-safar feel free to close this.

**Comment by beppe9000** [comment]
Thanks I'll look into that.
