### ISSUE TITLE
Add detection for reflection instance methods calls

### ISSUE THREAD

**Issue by MichalStrehovsky** [mono/linker#484]
Seems like because `MarkTypeUsedViaReflection` and `MarkSomethingUsedViaReflection` are disconnected, Linker cannot detect this pattern and preserve the method.

This pattern is often used in lightup scenarios.

**Comment by marek-safar** [comment]
This should also include commonly used pattern over generic types.

```
typeof(Foo<>).MakeGenericType(T1).GetMethod("SomeMethod")
```

**Comment by vitek-karas** [comment]
@MichalStrehovsky Can you please add a couple of samples which currently don't work and we would like to make them work? (I have to admit I can't figure out what exactly the title means).

**Comment by MichalStrehovsky** [comment]
The original title was "Detect Type.GetType("Foo").GetMethod("Bar")" but it got renamed since I created it. I think we can consider this fixed.
