### ISSUE TITLE
Support for RuntimeReflectionExtensions.GetRuntimeMethod

### ISSUE THREAD

**Issue by tzachshabtay** [mono/linker#55]
Reading on Xamarin's IOS linking (https://developer.xamarin.com/guides/ios/advanced_topics/linker/), and I'm guessing this is the tool they use to link (right?), they write that reflection is not supported by the linker, but if nameof is used (see also discussion here: https://github.com/autofac/Autofac/pull/841) can we add support for the linker to assume that the method in the nameof is being also being used and not strip it out?

**Comment by marek-safar** [comment]
nameof is unfortunatelly not recognisable at linker level, it's simple string constant for the linker but linker could recognise `GetRuntimeMethod`

**Comment by tzachshabtay** [comment]
Well, maybe the compiler can leave some metadata to the linker?
But yeah, supporting `GetRuntimeMethod` would also be awesome.

**Comment by tillig** [comment]
From autofac/Autofac#842 it looks like the real issue is more `GetRuntimeMethod` and reflection support than `nameof`.

**Comment by tzachshabtay** [comment]
Well, technically either of those (support for `nameof` or `GetRuntimeMethod`) would solve the issue for Autofac, it's just that support for `GetRuntimeMethod` seems much more practical as it doesn't need added support from the compiler.
