### ISSUE TITLE
[blazor] linker is not removing dead methods from blazor dlls

### ISSUE THREAD

**Issue by Lupusa87** [mono/linker#562]
I am creating latest version (P5) blazor template standalone project, adding methods (in several places) which are never used.

After build I decompile blazor.dll and all this methods are presented.

I expect that linker will remove methods which are not used anywhere but it does not.

Is this linker bug?

**Comment by Suchiman** [comment]
@Lupusa87 the startup assembly of blazor (and possibly all your direct project references) are considered roots, they don't get linked and keep everything alive they touch.

**Comment by Lupusa87** [comment]
@Suchiman Thank you for answer.

It can be lot of dead code in blazor app/libs as project goes complex and they will add extra size.
Why is it bad if linker will remove them too.

I understand that developer has control over his project and can remove or comment all dead code but it should be done manually (because I don't remember any tool for that purpose).

**Comment by Suchiman** [comment]
@Lupusa87 because it's pretty invasive if the linker starts removing your stuff that you may be using through reflection. It is assumed that you don't write dead code in your blazor project.
