### ISSUE TITLE
Unreferenced assemblies with "copy" action are not kept

### ISSUE THREAD

**Issue by sbomer** [mono/linker#576]
The linker loads the reference closure of the roots, and processes all of these references in subsequent steps. Assemblies that are not referenced will not be output, even if they were explicitly passed as "-p copy <assembly>".  Similar for `addbypassngen`.

A simple fix might be to post-process assemblies with "-p" actions that are outside the reference closure in OutputStep, but this will also miss some of the behavior in SweepStep to deal with type forwarders for example.

**Comment by marek-safar** [comment]
Could you please attach some form of a sample which demonstrates this issue?
