### ISSUE TITLE
VS2019 Fatal error in IL Linker

### ISSUE THREAD

**Issue by saqw3r** [mono/linker#727]
Earlier, I submitted a bug in Developer Community:
[VS2019 Fatal error in IL Linker](https://developercommunity.visualstudio.com/content/problem/583444/vs2019-fatal-error-in-il-linker.html)
but they referenced me to this project.
Could you check/review it, please.

**Comment by marek-safar** [comment]
This is an error in ILLinker but due to incomplete references send to the tool. Please report this issue in Blazor project.

The technical details

```
Cannot find declaration of exported type ‘System.Threading.Semaphore’ from the assembly ‘System.Threading, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a’
```

This error seems to be caused due to missing mscorlib reference which System.Threading depends on.

```
.class extern forwarder System.Threading.Semaphore
{
  .assembly extern mscorlib
}
```
