### ISSUE TITLE
Skip codepath Environment.OSVersion.Platform on publish trimmed with linker

### ISSUE THREAD

**Issue by jormenjanssen** [mono/linker#760]
The publish trimmed feature in .NET core 3 is not trimming code on specific code paths (see example below) which are  unable to get hit when published with specific runtime-rid e.g. windows and readytorun

Another approach would be #if but this has several disadvantages in Visual Studio etc.

```csharp
public static IServiceCollection AddSocketCAN(this IServiceCollection serviceCollection)
        {
            if (Environment.OSVersion.Platform != PlatformID.Unix)
                return serviceCollection;

            serviceCollection
                .AddSingleton<ICanFactory, SocketCanFactory>()
                .AddSingleton<ISafetyRequestProvider, UnixDiagramSafetyRequestProvider>();
            
            return serviceCollection;
        }

**Comment by marek-safar** [comment]
ILLinker for .NET 3 is not capable of rewriting method bodies

**Comment by jormenjanssen** [comment]
@marek-safar Any plans for this in .NET 5 or maybe an alternative based on attributes above the method ?

**Comment by marek-safar** [comment]
Yes we are working on more capabilities, see for example https://github.com/mono/linker/issues/752
