### ISSUE TITLE
Running with --deterministic creates identical GUIDs

### ISSUE THREAD

**Issue by vargaz** [mono/linker#770]
Run 
monolinker --deterministic -a hello.exe on the attached assemblies.
Result:
ikdasm output/hello.exe | grep MVID
// MVID: {EEA339DA-6B5E-4D4B-B255-BFEF95601890}
ikdasm output/foo.dll | grep MVID
// MVID: {EEA339DA-6B5E-4D4B-B255-BFEF95601890}

**Comment by vargaz** [comment]
[a.zip](https://github.com/mono/linker/files/3674800/a.zip)

**Comment by vargaz** [comment]
@jbevain

**Comment by vargaz** [comment]
Might be caused by:
https://github.com/jbevain/cecil/pull/587

**Comment by marek-safar** [comment]
@jbevain could you help us with it?

**Comment by jeromelaban** [comment]
Here's a fix for this issue: https://github.com/jbevain/cecil/pull/622, will need to be pulled into the linker.

**Comment by jeromelaban** [comment]
The fix is merged in Cecil, is there something special to do to update the submodule in the linker ?

**Comment by vargaz** [comment]
Thanks for the fix.

Need to wait until
https://github.com/mono/cecil/pull/26
is merged, then need to bump mono to use that rev.

**Comment by vargaz** [comment]
https://github.com/mono/mono/pull/17428

**Comment by vargaz** [comment]
Should be fixed now. Thanks.
