### ISSUE TITLE
PreserveDependencyAttribute should support "*" for members

### ISSUE THREAD

**Issue by stephentoub** [mono/linker#799]
Or some alternative way of saying "keep everything on the target type".  Example where this is helpful:
https://github.com/dotnet/corefx/blob/bc1f6ae4e757251c8691fe94e68617ce1516e684/src/System.Linq.Expressions/src/System/Runtime/CompilerServices/CallSite.cs#L280-L323
https://github.com/dotnet/corefx/blob/bc1f6ae4e757251c8691fe94e68617ce1516e684/src/System.Linq.Expressions/src/System/Dynamic/UpdateDelegates.Generated.cs
Here lots of methods are potentially being used, representing all methods on the type.  Instead of explicitly having 40 PreserveDependency attributes, I could have 1, and if the target type ever added more arg lengths, this wouldn't need to be updated.

(Ideally it would use the same syntax as the ILLinkTrim.xml files, which support * for pattern matching.)

**Comment by marek-safar** [comment]
I think supporting the same syntax as in xml descriptors make sense.
