### ISSUE TITLE
TypeConverter attributes on properties aren't respected

### ISSUE THREAD

**Issue by stephentoub** [mono/linker#800]
The linker has special logic for TypeConverters, but only as applied to types apparently.  It's not respecting, e.g.
https://github.com/dotnet/corefx/blob/b49a8a9be1d53cd9e50cb68fd8540be25c65d433/src/System.Data.Common/src/System/Data/DataColumn.cs#L475

**Comment by Gnbrkm41** [comment]
![image](https://user-images.githubusercontent.com/42944058/68081589-b7bf0280-fe53-11e9-882b-c657e687984d.png)

https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/DataColumn.cs#L478

Are these still necessary?

**Comment by stephentoub** [comment]
Until corefx consumes a linker with this change, yes.
