### ISSUE TITLE
Need a way for something to survive assembly trimming only

### ISSUE THREAD

**Issue by stephentoub** [mono/linker#802]
I'd like to be able to mark an individual instance of PreserveDependencyAttribute as being removable as part of trimming.

Example use case:
```C#
[PreserveDependency("ToServerString", RemoveAttribute = true)]
public class Cookie
{
    ...
    internal string ToServerString() { ... }
}
```
Currently in corefx, Cookie.ToServerString (in System.Net.Primtives.dll) is non-public and has no consumers in the assembly, but it is used via reflection from HttpListener.  When we build System.Net.Primitives.dll, we thus need to keep ToServerString around, but when building and trimming at the app-level, ToServerString is only needed if a PreserveDependency attribute from HttpListener keeps it around.  To keep ToServerString in the System.Net.Primitives build, we currently only have two options: use an ILLinkTrim.xml file, or use a PreserveDependency attribute from something else in the assembly.  If we use ILLinkTrim.xml, then ToServerString will survive into all app builds, even when HttpListener isn't used.  If we use PreserveDependency, we need to put the attribute somewhere (the most natural place would be on Cookie itself: https://github.com/mono/linker/issues), but then since we in general in corefx need dependencies to be preserved into the app build, this will also end up keeping it around as long as Cookie is used.  We can build System.Net.Primitives to specially not set `--keep-dep-attributes`, but that's a large assembly-wide hammer and will end up impacting any other uses of the attribute in the assembly.

**Comment by marek-safar** [comment]
I am not sure I follow why is this needed. I think we discussed that we need to run linker on the real assemblies at the end of the SDK build so it can actually keep the non-public dependencies. Looking at `CookieExtensions` implementation the reflection code should just be detectable out of the box so not sure why would we need this there.

**Comment by stephentoub** [comment]
@marek-safar, I'm not following.  Are you saying that you want to trim all of the SDK assemblies by effectively linking the entire SDK?

**Comment by marek-safar** [comment]
Yes, single pass on entire SDK of real assemblies (dlls with IL code, no reference assemblies involved at all).

**Comment by spouliot** [comment]
That sounds like what the _old_ `[Preserve (Conditional=true)] does.

If something marks the `Cookie` type (which is not preserved) then all conditionally preserved members will be kept around.

**Comment by marek-safar** [comment]
We resolved this by changing the build process in dotnet/runtime
