### ISSUE TITLE
Rename PreserveDependencyAttribute

### ISSUE THREAD

**Issue by stephentoub** [mono/linker#805]
I would like us to consider renaming PreserveDependencyAttribute, or if that's too breaking, add an additional name that the linker recognizes.

"PreserveDependency" speaks to the action a particular tool (in this case, the linker) is going to take based on the information provided, but really the attribute is used to say "this member has a dependency on that member", and a consuming tool can factor that information in however it likes.  Thus, a name like "HasDependencyOn" or "ImplicitDependency" or "MemberDependency" or something that speaks to the state rather than to the follow-on action would be good.

This will become more important should we choose to expose this publicly: .https://github.com/dotnet/corefx/issues/41201.

**Comment by marek-safar** [comment]
I'd like this attribute to be publicly available, perhaps we should have a discussion over there. The attribute name is still used only internally so renaming is still an option.

**Comment by MattWhilden** [comment]
Any update around this attribute? There's some desire to use it to resolve https://github.com/dotnet/runtime/issues/978. 

If y'all think that PreserveDependency will be around for a while I may just teach the .NET Native compiler about that for the time being. Thoughts?

**Comment by stephentoub** [comment]
I expect it'll be around in some form, and hopefully some variant of it ship in .NET 5, but it's still experimental and I expect we'll see some changes / additions around it.

**Comment by marek-safar** [comment]
Closing as the work is now tracked at #1148
