### ISSUE TITLE
Linker not respecting the .assembly extern clauses

### ISSUE THREAD

**Issue by tlakollo** [mono/linker#815]
After linker version has been refreshed in corefx repository the System.Runtime.CompilerServices.Unsafe.dll has diffs in the trimmed code

The expected behavior is that linker will try to use a certain System.Runtime version
```
.assembly extern System.Runtime
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:2:1:0
}
```
Unless there is a .assembly extern clause that specifies something different. In the case of System.Runtime.CompilerServices.Unsafe.dll there is a clause that defines the version to be used as ver. 4:0:0:0
https://github.com/dotnet/corefx/blob/26d7b6626ab0385a1158e674855f81ab73f628e0/src/System.Runtime.CompilerServices.Unsafe/src/include/netcoreapp/coreassembly.h

In the past the linker will only publish the 4:0:0:0 information
```
.assembly extern System.Runtime
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:0:0:0
}
```
Now the linker is generating 
```
.assembly extern System.Runtime
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:0:0:0
}
.assembly extern System.Runtime as System.Runtime_1
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:2:1:0
}
```
and then using System.Runtime_1 for the rest of the calls, which means we are actually using version 4:2:1:0 instead of 4:0:0:0
So far there is no proof that this is causing compatibility issues, but is a different behavior for the linker that needs to be reviewed

**Comment by marek-safar** [comment]
Fixed in master
