### ISSUE TITLE
InvalidOperationException: No entry methods in dotnet/runtime build

### ISSUE THREAD

**Issue by akoeplinger** [mono/linker#905]
See https://dev.azure.com/dnceng/public/_build/results?buildId=474524&view=logs&jobId=214ce225-49cc-5240-836e-21c9eea7fd5c&j=de7d46dd-46cc-5631-ddd7-a3c134a1a855&t=886708a9-f90e-5e10-9587-aa9f4cd21d9b from dotnet/runtime#1088

```
  Fatal error in IL Linker
  Unhandled exception. System.InvalidOperationException: No entry methods
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
/Users/runner/runners/2.163.1/work/1/s/eng/illink.targets(132,5): error MSB6006: "dotnet" exited with code 134. [/Users/runner/runners/2.163.1/work/1/s/src/libraries/shims/generated/netstandard.csproj]
##[error]eng/illink.targets(132,5): error MSB6006: "dotnet" exited with code 134.
```

/cc @marek-safar

**Comment by safern** [comment]
@akoeplinger is someone already investigating this?

Every new update PR from arcade and vstest into runtime contains an update from the linker and therefore we need to remove that commit for it to be able to go in. We could set the arcade and vstest updates to not be batched on the time being, but I don't know if it is worth the effort if someone is already working on this.

https://github.com/dotnet/runtime/pull/1524
