### ISSUE TITLE
Reflection patterns can not resolve assemblies outside of the reference closure

### ISSUE THREAD

**Issue by sbomer** [mono/linker#943]
When a supported reflection pattern references an assembly that is part of the linker input set, but not in the reference closure of any roots (and thus not loaded into the LinkContext assemblies by LoadReferencesStep or any other step that comes before MarkStep), the pattern will fail to resolve. Since simple reflection patterns are often used for activation without a build-time dependency, this seems like something worth supporting. See https://github.com/dotnet/sdk/issues/4017 for the original issue with a repro.

https://github.com/mono/linker/issues/843 is a similar issue where `PreserveDependency` doesn't cause xml roots from the referenced assembly to be processed.

If we fix this, we should be able to undo https://github.com/dotnet/runtime/pull/32023.

**Comment by marek-safar** [comment]
I believe this should be fixed. @sbomer could you please undo the runtime change so we can fully verify this and close ?

**Comment by sbomer** [comment]
Fixed by https://github.com/mono/linker/pull/1666, runtime workarounds removed in https://github.com/dotnet/runtime/pull/49523.
