### ISSUE TITLE
Add pattern recognition for calls to RuntimeHelpers.RunClassConstructor

### ISSUE THREAD

**Issue by vitek-karas** [mono/linker#970]
Linker may decide to trim static `.cctor` from a class if it doesn't find a need to keep it. Calling `System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor` is in such case unsafe as it requires the static `.cctor` to be present to work correctly.

Linker should be able to analyze simple patterns calling the `RunClassConstructor` and include the necessary static `.cctor`. The minimum pattern to support should be:
``` C#
RuntimeHelpers.RunClassConstructor(typeof(MyClass));
```

Once implement we can basically revert this change in CoreLib dotnet/runtime#31718.
This is a preferred solution to the changes suggested in #966.

**Comment by marek-safar** [comment]
Interestingly this API is used more often than I thought (2 hits in libraries, 1 in coreclr).
