### ISSUE TITLE
monolinker.sln is broken

### ISSUE THREAD

**Issue by mrvoorhe** [mono/linker#973]
When I open monolinker.sln and build it builds illink.exe.

@sbomer how is `MonoBuild` supposed to be defined when using `monolinker.sln`?

**Comment by akoeplinger** [comment]
Hmm that's probably my fault from the changes in https://github.com/mono/linker/pull/937. We pass `/p:MonoBuild=true` when building monolinker.sln there.

Can you please try whether adding this to Directory.Build.props works:

```diff
diff --git a/Directory.Build.props b/Directory.Build.props
index 86a0684..421b5bd 100644
--- a/Directory.Build.props
+++ b/Directory.Build.props
@@ -1,6 +1,10 @@
 <Project>
+  <PropertyGroup>
+    <MonoBuild Condition="'$(MonoBuild)' == '' and '$(SolutionName)' == 'monolinker'">true</MonoBuild>
+  </PropertyGroup>
+
   <Import Project="Sdk.props" Sdk="Microsoft.DotNet.Arcade.Sdk" Condition="'$(MonoBuild)' == ''" />
   <PropertyGroup>
     <IsPackable>false</IsPackable>
   </PropertyGroup>
```
