### ISSUE TITLE
Add option to output all P/Invokes from managed code

### ISSUE THREAD

**Issue by marek-safar** [mono/linker#985]
There should be a new option `--output-pinvokes FILE` which when used will generate output file (JSON) which will include the following data

```json
{
  "entryPoint" : "MessageBox",
  "moduleName" : "user32.dll"
}
```

**Comment by MichalStrehovsky** [comment]
What will this list be used for? Should it also include information about whether the app contains a call to `NativeLibrary.SetDllImportResolver` that could redirect the module part to any other file at runtime?

**Comment by marek-safar** [comment]
One of the purposes will be to use the data for static linking

**Comment by vitek-karas** [comment]
Is this for AOT scenarios?
If so, we could mark `NatvieLibrary.SetDllImportResolver` as potentially dangerous for AOT - if AOT uses static linking of native dependencies then it's definitely dangerous.

**Comment by marek-safar** [comment]
Yes, this primary for static linking AOT scenarios

**Comment by marek-safar** [comment]
Implemented for .net5
