### ISSUE TITLE
Fix Debug.Asserts related to reflection pattern analysis

### ISSUE THREAD

**Issue by mrvoorhe** [mono/linker#995]
I can't simply run all of the tests with a debug build on Windows anymore.  I'm hitting debug assert pop ups which I then have to click ignore on in order for the tests to continue running. 

Running the tests under `CoreLinkTests` can reproduce the problem.

There are 2 aspects I'd like to point out.

First, the Debug.Assert pop up is useless.  It just displays a stack.  When I replace the assert with an exception I get this much nicer error message that tells me what method was involved as well as the stack trace.

```
Mono.Linker.MarkException : Error processing method: 'System.Int32 System.AppDomain::ActivateApplication()' in assembly: 'CommonLanguageRuntimeLibrary'
  ----> System.InvalidOperationException : A reflection pattern was analyzed, but no result was reported.
```

And as an added benefit, the unit tests keep running.  Given that the `Debug.Assert` are inside`#if DEBUG` I don't see any benefit to using `Debug.Assert` over throwing.

Secondly, if we are going to have special asserts for debug builds, then CI should build and run tests in debug as well to ensure that we don't have debug only test failures.  I don't know if the tests are currently ran on debug or release builds but it would be worth checking.

cc @vitek-karas

**Comment by vitek-karas** [comment]
@mrvoorhe Sorry for my confusion - what do you mean by "run tests on Debug build on Windows". I just tried running the `illink.sln` on Windows on Debug and it works.

I honestly don't know how to run the `monolinker.sln` on Windows.

How are you running it - so that I can reproduce the failures.

**Comment by mrvoorhe** [comment]
I believe illink.sln is linking the tests against .net core class libraries which apparently doesn't have any patterns that trip this assert.

Reproducing this specific one likely requires linking against the .NET Framework assemblies which `monolinker.sln` does on windows.

The workflow I follow is

1) Open monolinker.sln with Rider
2) Leave the build configuration as Debug
3) Run the tests from Rider's Test Explorer.

I'm sure you could repro with Visual Studio and some nunit test runner.

I haven't looked at the method that is causing the issue but I suspect you could look at the .NET Framework reference source or open the .NET Framework mscorlib in ILSpy and derive a test case that reproduces the issue

**Comment by marek-safar** [comment]
@mrvoorhe are you running this against .net or mono framework? Could you link to System.Int32 System.AppDomain::ActivateApplication() implementation?

**Comment by mrvoorhe** [comment]
On windows monolinker.sln will link the tests against the .NET Framework.

Here is the code from the method that failed.

```
[SecuritySafeCritical]
private int ActivateApplication()
{
	ObjectHandle objectHandle = Activator.CreateInstance(CurrentDomain.ActivationContext);
	return (int)objectHandle.Unwrap();
}
```

Any comments on switching to throw instead of debug.assert?  Given that it would be inside a #if DEBUG I don't see any advantage to using Debug.Assert over throw.
